### ISSUE TITLE
Bump up snowflake-connector-python version requirement to at least 2.4.0

### ISSUE THREAD

**Issue by ClassyLion** [fishtown-analytics/dbt#3262] opened 2021-04-14 17:30 UTC
### Describe the feature
Want to install snowflake-connector-python 2.4.0+ to support PyArrow 3.0.0.

### Additional context
 Currently, the issue I see when I try to install a newer version is:
```
dbt-snowflake 0.19.1 requires snowflake-connector-python[secure-local-storage]==2.3.6, but you have snowflake-connector-python 2.4.2 which is incompatible.
``` 

### Who will this benefit?
Describe alternatives you've considered
I think we can fix this by not pinning the snowflake-connector-python version to 2.3.6 specifically, but setting the version constraint to snowflake-connector-python>=2.3.6. However we should ensure that things don't break with a newer version of the snowflake-connector-python and that the test suite still pass.

Who will this benefit?
Anyone trying to install dbt-snowflake alongside the Airflow snowflake provider

This would also benefit those who would want to use Python 3.9, as support for it was added in version 2.4.0.

### Are you interested in contributing this feature?
I am interested in contributing to this feature, to the extent of my almost non-existant experience and knowledge.

**Comment by jtcohen6** [comment] 2021-04-14 21:26
Hey @ClassyLion, I totally agree! As of https://github.com/fishtown-analytics/dbt/pull/3148, we've already upgraded the required version of `snowflake-connector-python` in the `develop` branch:

https://github.com/fishtown-analytics/dbt/blob/bfdf7f01b55a90ea8292e1c537b6cf44faa412ab/plugins/snowflake/setup.py#L48-L53

The next minor version of dbt (v0.20.0) will be compatible with python 3.9, PyArrow 3.0.0, and a whole bunch more.

I'm going to close this issue as a duplicate of https://github.com/fishtown-analytics/dbt/issues/3170, and as something that's been resolved :)

**Closed by jtcohen6** 2021-04-14 21:26 UTC
Labels: duplicate, enhancement

**Comment by ClassyLion** [comment] 2021-04-15 05:46
Thank you for the response. My mistake in not finding it earlier. When will the next minor version be released?

**Comment by jtcohen6** [comment] 2021-04-15 17:48
Hoping to have an initial beta version in the next few weeks!
