### ISSUE TITLE
SQL Headers Are Not Injected During BigQuery Incremental Loads 

### ISSUE THREAD

**Issue by garethqb** [fishtown-analytics/dbt#2194] opened 2020-03-11 01:19 UTC
### Describe the bug
The SQL header feature works for injecting temporary functions into BigQuery `create table as` and `create view as`, but not in the `merge` command. Jeremy pointed out that this should now starting working in dbt version 0.16.0 after the rework to using BigQuery `merge`.

### Steps To Reproduce
1. Create dbt model with sql header
2. Run dbt model with `--full-refresh`
3. Run dbt model without a full refresh - error occurs.

### Expected behavior
The `create temp function` sql statements injected in compiled code to be referenced by the merge statement.

### Screenshots and log output
```
14:37:14 | Finished running 3 incremental models in 77.28s.

Completed with 1 error and 0 warnings:

Database Error in model tf_app_session_feature_group (models/_transform/product/tf_app_session_feature_group.sql)
  Function not found: JsonExtractSessionTypes at [1785:9]
  compiled SQL at target/run/quibi_analytics/_transform/product/tf_app_session_feature_group.sql
```

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.15.2
   latest version: 0.15.2

Up to date!
```

**The operating system you're using:**
macOS Mojave 10.14.6

**The output of `python --version`:**
Python 2.7.16

**Comment by clausherther** [comment] 2020-03-12 20:43
Is this a duplicate of #2136 ?

**Comment by drewbanin** [comment] 2020-03-18 18:53
@clausherther it is! See https://github.com/fishtown-analytics/dbt/pull/2200 for the fix. We're not going to ship this for 0.16.0, but we can do it for 0.16.1

**Closed by drewbanin** 2020-03-18 18:53 UTC
Labels: duplicate
