### ISSUE TITLE
Update versions for required libraries for dbt-bigquery

### ISSUE THREAD

**Issue by ClassyLion** [fishtown-analytics/dbt#3281] opened 2021-04-20 14:25 UTC
### Describe the feature
Bump up the dbt-bigquery required version of google-core-api to at least 1.25.1 and version of google-cloud-bigquery to at least 2.6.2.

### Who will this benefit?
google-core-api version would add compatibility with the latest version of Apache Airflow and google-cloud-bigquery version adds fixes for Opentelemetry warnings in log files.

### Are you interested in contributing this feature?
I am interested in contributing, but I don't know if my limited experience and skillset would prove to be beneficial.

**Comment by jtcohen6** [comment] 2021-04-20 17:03
Hey @ClassyLion, thanks for opening! It's a totally reasonable request.

We recently (https://github.com/fishtown-analytics/dbt/commit/d6dd968c4f5dfb8fdb50f3d6de6898bebe2cdd1b) increased the upper limit on all Google dependencies, including `google-core-api`—to the next major version, in fact:
https://github.com/fishtown-analytics/dbt/blob/33dc970859f5535610b2335f8cad5369095a686c/plugins/bigquery/setup.py#L51-L54

This change is on the `develop` branch now, and it will be included in the next minor version of dbt (v0.20.0). Setting the upper bound at major versions should also allow us to avoid re-bumping these dependencies in every dbt minor version to come.

I'm going to close this issue as a duplicate of https://github.com/fishtown-analytics/dbt/issues/3155.

**Closed** 2021-04-20 17:03 UTC
Labels: enhancement

**Comment by ClassyLion** [comment] 2021-04-20 17:13
Apology for a duplicate issue. Thanks for the response and can't wait for the next minor version of DBT. This is the second change I'm waiting for now. 😄
