### ISSUE TITLE
Support model selection based on materialization type

### ISSUE THREAD

**Issue by azhard** [fishtown-analytics/dbt#2563] opened 2020-06-17 17:20 UTC
### Describe the feature
Current model selection syntax works with selecting based on model names, sources, tags, packages, and paths. These solve the majority of potential use cases but adding the ability to select models based on a materialization type would be very handy.

A specific example where that can be used: my team's dbt setup currently auto-runs changed models on production when an MR gets merged to `master`, however we realistically only want to deploy changed views and not to cause incremental materializations for example as those are typically based on a schedule.

I imagine as an actual CLI command this would look something like when implemented:
```
dbt run --models materialization:view
````

### Describe alternatives you've considered
This same behaviour can be achieved if a user tags all view (or non-view) models but this is more cumbersome so not ideal.

### Additional context
This feature should be supported across databases.

### Who will this benefit?
Any dbt user who wants to trigger runs based on a materialization type.

**Comment by drewbanin** [comment] 2020-06-17 18:04
hey @azhard - thanks for opening this issue. This is a dupe of https://github.com/fishtown-analytics/dbt/issues/2425, prioritized for our next feature release. Closing this!

**Closed by drewbanin** 2020-06-17 18:04 UTC
Labels: enhancement

**Comment by azhard** [comment] 2020-06-17 18:05
Awesome! Thanks @drewbanin
