### ISSUE TITLE
dbt test: add new --bespoke & --generic flags and deprecate --schema & --data?

### ISSUE THREAD

**Issue by swanderz** [fishtown-analytics/dbt#3507] opened 2021-06-29 00:23 UTC
looking at the vnext docs, looks like schema -> generic and data -> bespoke. perhaps this should be reflected in the CLI flags for `dbt test`?

https://github.com/fishtown-analytics/dbt/blob/41610b822cd7e87f6ba8acfb3d9bfab1903a9267/core/dbt/main.py#L699-L712

**Comment by jtcohen6** [comment] 2021-06-29 01:04
@swanderz You're right. The only reasons we haven't done this yet:
- We haven't landed firmly on new names. I feel pretty good about `generic`, but `bespoke` is not quite right.
- There are still a bunch of places within the codebase where this renaming would need to take place.

I'm going to close this as a duplicate of #3234 — would love to hear your thoughts over there!

**Closed by jtcohen6** 2021-06-29 01:04 UTC
Labels: duplicate
