### ISSUE TITLE
pip-compile: DBT requires contradictory packages

### ISSUE THREAD

**Issue by TjrGithub** [fishtown-analytics/dbt#2674] opened 2020-07-31 12:08 UTC
### Describe the bug
dbt seems to need incompatible requirements when installed from pip.
I'm not sure if this is a dbt or a pip-compile bug.

### Steps To Reproduce
```shell
$ cat requirements.in 
dbt
$ pip-compile requirements.in 
Traceback (most recent call last):
  File "/home/tjb/Dokumente/cologne_2018/Karriere/optiker-datenanalyse/bnb-datenanalyse/rw_elt/venv/pytest/bin/pip-compile", line 8, in <module>
    sys.exit(cli())
  File "/home/tjb/Dokumente/cologne_2018/Karriere/optiker-datenanalyse/bnb-datenanalyse/rw_elt/venv/pytest/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/tjb/Dokumente/cologne_2018/Karriere/optiker-datenanalyse/bnb-datenanalyse/rw_elt/venv/pytest/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/tjb/Dokumente/cologne_2018/Karriere/optiker-datenanalyse/bnb-datenanalyse/rw_elt/venv/pytest/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tjb/Dokumente/cologne_2018/Karriere/optiker-datenanalyse/bnb-datenanalyse/rw_elt/venv/pytest/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/tjb/Dokumente/cologne_2018/Karriere/optiker-datenanalyse/bnb-datenanalyse/rw_elt/venv/pytest/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/tjb/Dokumente/cologne_2018/Karriere/optiker-datenanalyse/bnb-datenanalyse/rw_elt/venv/pytest/lib/python3.7/site-packages/piptools/scripts/compile.py", line 444, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File "/home/tjb/Dokumente/cologne_2018/Karriere/optiker-datenanalyse/bnb-datenanalyse/rw_elt/venv/pytest/lib/python3.7/site-packages/piptools/resolver.py", line 164, in resolve
    "This is likely a bug.".format(max_rounds=max_rounds)
RuntimeError: No stable configuration of concrete packages could be found for the given constraints after 10 rounds of resolving.
This is likely a bug.
```

### Expected behavior
pip should find a set of compatible packages to install dbt.
A few days ago, the same script used to work, and pip-compile resulted in:
```shell
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile requirements.in
#
agate==1.6.1              # via dbt-core
asn1crypto==1.3.0         # via oscrypto, snowflake-connector-python
attrs==19.3.0             # via jsonschema
azure-common==1.1.25      # via azure-storage-blob, azure-storage-common, dbt-snowflake, snowflake-connector-python
azure-storage-blob==2.1.0  # via dbt-snowflake, snowflake-connector-python
azure-storage-common==2.1.0  # via azure-storage-blob
babel==2.8.0              # via agate
boto3==1.11.17            # via dbt-redshift, snowflake-connector-python
botocore==1.14.17         # via boto3, dbt-redshift, s3transfer, snowflake-connector-python
cachetools==4.1.1         # via google-auth
certifi==2020.6.20        # via requests, snowflake-connector-python
cffi==1.13.2              # via cryptography, dbt-core, snowflake-connector-python
chardet==3.0.4            # via requests
colorama==0.4.3           # via dbt-core
cryptography==2.9.2       # via azure-storage-common, dbt-snowflake, pyopenssl, snowflake-connector-python
dbt-bigquery==0.17.1      # via dbt
dbt-core==0.17.1          # via dbt, dbt-bigquery, dbt-postgres, dbt-redshift, dbt-snowflake
dbt-postgres==0.17.1      # via dbt, dbt-redshift
dbt-redshift==0.17.1      # via dbt
dbt-snowflake==0.17.1     # via dbt
dbt==0.17.1               # via -r requirements.in
decorator==4.4.2          # via networkx
docutils==0.15.2          # via botocore
google-api-core==1.16.0   # via dbt-bigquery, google-cloud-bigquery, google-cloud-core
google-auth==1.19.2       # via google-api-core, google-cloud-bigquery
google-cloud-bigquery==1.24.0  # via dbt-bigquery
google-cloud-core==1.3.0  # via dbt-bigquery, google-cloud-bigquery
google-resumable-media==0.5.1  # via google-cloud-bigquery
googleapis-common-protos==1.6.0  # via dbt-bigquery, google-api-core
hologram==0.0.7           # via dbt-core
idna==2.8                 # via dbt-core, requests, snowflake-connector-python
ijson==2.6.1              # via snowflake-connector-python
importlib-metadata==1.7.0  # via jsonschema
isodate==0.6.0            # via agate, dbt-core
jinja2==2.11.2            # via dbt-core
jmespath==0.10.0          # via boto3, botocore
json-rpc==1.13.0          # via dbt-core
jsonschema==3.1.1         # via hologram
leather==0.3.3            # via agate
logbook==1.5.3            # via dbt-core
markupsafe==1.1.1         # via jinja2
minimal-snowplow-tracker==0.0.2  # via dbt-core
networkx==2.4             # via dbt-core
oscrypto==1.2.0           # via snowflake-connector-python
parsedatetime==2.6        # via agate
protobuf==3.11.3          # via dbt-bigquery, google-api-core, google-cloud-bigquery, googleapis-common-protos
psycopg2-binary==2.8.5    # via dbt-postgres
pyasn1-modules==0.2.8     # via google-auth
pyasn1==0.4.8             # via pyasn1-modules, rsa
pycparser==2.20           # via cffi
pycryptodomex==3.9.8      # via snowflake-connector-python
pyjwt==1.7.1              # via snowflake-connector-python
pyopenssl==19.1.0         # via snowflake-connector-python
pyrsistent==0.16.0        # via jsonschema
python-dateutil==2.8.1    # via azure-storage-common, botocore, hologram
python-slugify==4.0.1     # via agate
pytimeparse==1.1.8        # via agate
pytz==2020.1              # via babel, google-api-core, snowflake-connector-python
pyyaml==5.3.1             # via dbt-core
requests==2.22.0          # via azure-storage-common, dbt-core, google-api-core, minimal-snowplow-tracker, snowflake-connector-python
rsa==4.6                  # via google-auth
s3transfer==0.3.3         # via boto3
six==1.15.0               # via agate, cryptography, dbt-bigquery, google-api-core, google-auth, google-cloud-bigquery, google-resumable-media, isodate, jsonschema, leather, minimal-snowplow-tracker, protobuf, pyopenssl, pyrsistent, python-dateutil
snowflake-connector-python==2.2.1  # via dbt-snowflake
sqlparse==0.3.1           # via dbt-core
text-unidecode==1.3       # via python-slugify
typing-extensions==3.7.4.2  # via dbt-core
urllib3==1.25.9           # via botocore, dbt-snowflake, requests, snowflake-connector-python
werkzeug==0.16.1          # via dbt-core
zipp==3.1.0               # via importlib-metadata

# The following packages are considered to be unsafe in a requirements file:
# setuptools
```

### System information
**Which database are you using dbt with?**
- [X] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
It doesn't install, so no version :-(

**The operating system you're using:**
Ubuntu Linux 19.10

**The output of `python --version`:**
Python 3.7.5

### Additional context
This is the virtualenv runnign pip-compile:
```shell
$ pip freeze
astroid==2.4.2
attrs==19.3.0
click==7.1.2
flake8==3.8.3
importlib-metadata==1.7.0
isort==4.3.21
lazy-object-proxy==1.4.3
mccabe==0.6.1
more-itertools==8.4.0
mypy==0.782
mypy-extensions==0.4.3
packaging==20.4
path==14.0.1
pip-tools==5.2.1
pkg-resources==0.0.0
pluggy==0.13.1
psycopg2==2.8.5
py==1.9.0
pycodestyle==2.6.0
pydocstyle==5.0.2
pyflakes==2.2.0
pylint==2.5.3
pyparsing==2.4.7
pytest==5.4.3
python-dateutil==2.8.1
ruamel.yaml==0.16.10
ruamel.yaml.clib==0.2.0
six==1.15.0
snowballstemmer==2.0.0
strictyaml==1.0.6
toml==0.10.1
typed-ast==1.4.1
typing-extensions==3.7.4.2
wcwidth==0.2.5
wrapt==1.12.1
zipp==3.1.0
```

**Comment by jtcohen6** [comment] 2020-07-31 14:17
Hi @TjrGithub, I'm unable to reproduce this error. I created a new virtual environment to try a fresh installation of dbt from pip, and everything worked fine. I installed pip-tools, created a `requirements.in` file containing dbt + all the packages you list from your virtualenv, and got a successful result:

```
$ cat requirements.in
dbt
astroid==2.4.2
attrs==19.3.0
click==7.1.2
flake8==3.8.3
importlib-metadata==1.7.0
isort==4.3.21
lazy-object-proxy==1.4.3
mccabe==0.6.1
more-itertools==8.4.0
mypy==0.782
mypy-extensions==0.4.3
packaging==20.4
path==14.0.1
pip-tools==5.2.1
pluggy==0.13.1
psycopg2==2.8.5
py==1.9.0
pycodestyle==2.6.0
pydocstyle==5.0.2
pyflakes==2.2.0
pylint==2.5.3
pyparsing==2.4.7
pytest==5.4.3
python-dateutil==2.8.1
ruamel.yaml==0.16.10
ruamel.yaml.clib==0.2.0
six==1.15.0
snowballstemmer==2.0.0
strictyaml==1.0.6
toml==0.10.1
typed-ast==1.4.1
typing-extensions==3.7.4.2
wcwidth==0.2.5
wrapt==1.12.1
zipp==3.1.0
```
```
$ pip-compile requirements.in
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile requirements.in
#
agate==1.6.1              # via dbt-core
asn1crypto==1.4.0         # via oscrypto, snowflake-connector-python
astroid==2.4.2            # via -r requirements.in, pylint
attrs==19.3.0             # via -r requirements.in, jsonschema, pytest
azure-common==1.1.25      # via azure-storage-blob, azure-storage-common, dbt-snowflake, snowflake-connector-python
azure-storage-blob==2.1.0  # via dbt-snowflake, snowflake-connector-python
azure-storage-common==2.1.0  # via azure-storage-blob
babel==2.8.0              # via agate
boto3==1.11.17            # via dbt-redshift, snowflake-connector-python
botocore==1.14.17         # via boto3, dbt-redshift, s3transfer, snowflake-connector-python
cachetools==4.1.1         # via google-auth
certifi==2020.6.20        # via requests, snowflake-connector-python
cffi==1.13.2              # via cryptography, dbt-core, snowflake-connector-python
chardet==3.0.4            # via requests
click==7.1.2              # via -r requirements.in, pip-tools
colorama==0.4.3           # via dbt-core
cryptography==2.9.2       # via azure-storage-common, dbt-snowflake, pyopenssl, snowflake-connector-python
dbt-bigquery==0.17.2      # via dbt
dbt-core==0.17.2          # via dbt, dbt-bigquery, dbt-postgres, dbt-redshift, dbt-snowflake
dbt-postgres==0.17.2      # via dbt, dbt-redshift
dbt-redshift==0.17.2      # via dbt
dbt-snowflake==0.17.2     # via dbt
dbt==0.17.2               # via -r requirements.in
decorator==4.4.2          # via networkx
docutils==0.15.2          # via botocore
flake8==3.8.3             # via -r requirements.in
google-api-core==1.16.0   # via dbt-bigquery, google-cloud-bigquery, google-cloud-core
google-auth==1.20.0       # via google-api-core, google-cloud-bigquery
google-cloud-bigquery==1.24.0  # via dbt-bigquery
google-cloud-core==1.3.0  # via dbt-bigquery, google-cloud-bigquery
google-resumable-media==0.5.1  # via google-cloud-bigquery
googleapis-common-protos==1.6.0  # via dbt-bigquery, google-api-core
hologram==0.0.7           # via dbt-core
idna==2.8                 # via dbt-core, requests, snowflake-connector-python
ijson==2.6.1              # via snowflake-connector-python
importlib-metadata==1.7.0  # via -r requirements.in, jsonschema
isodate==0.6.0            # via agate, dbt-core
isort==4.3.21             # via -r requirements.in, pylint
jinja2==2.11.2            # via dbt-core
jmespath==0.10.0          # via boto3, botocore
json-rpc==1.13.0          # via dbt-core
jsonschema==3.1.1         # via hologram
lazy-object-proxy==1.4.3  # via -r requirements.in, astroid
leather==0.3.3            # via agate
logbook==1.5.3            # via dbt-core
markupsafe==1.1.1         # via jinja2
mccabe==0.6.1             # via -r requirements.in, flake8, pylint
minimal-snowplow-tracker==0.0.2  # via dbt-core
more-itertools==8.4.0     # via -r requirements.in, pytest
mypy-extensions==0.4.3    # via -r requirements.in, mypy
mypy==0.782               # via -r requirements.in
networkx==2.4             # via dbt-core
oscrypto==1.2.1           # via snowflake-connector-python
packaging==20.4           # via -r requirements.in, pytest
parsedatetime==2.6        # via agate
path==14.0.1              # via -r requirements.in
pip-tools==5.2.1          # via -r requirements.in
pluggy==0.13.1            # via -r requirements.in, pytest
protobuf==3.11.3          # via dbt-bigquery, google-api-core, google-cloud-bigquery, googleapis-common-protos
psycopg2-binary==2.8.5    # via dbt-postgres
psycopg2==2.8.5           # via -r requirements.in
py==1.9.0                 # via -r requirements.in, pytest
pyasn1-modules==0.2.8     # via google-auth
pyasn1==0.4.8             # via pyasn1-modules, rsa
pycodestyle==2.6.0        # via -r requirements.in, flake8
pycparser==2.20           # via cffi
pycryptodomex==3.9.8      # via snowflake-connector-python
pydocstyle==5.0.2         # via -r requirements.in
pyflakes==2.2.0           # via -r requirements.in, flake8
pyjwt==1.7.1              # via snowflake-connector-python
pylint==2.5.3             # via -r requirements.in
pyopenssl==19.1.0         # via snowflake-connector-python
pyparsing==2.4.7          # via -r requirements.in, packaging
pyrsistent==0.16.0        # via jsonschema
pytest==5.4.3             # via -r requirements.in
python-dateutil==2.8.1    # via -r requirements.in, azure-storage-common, botocore, hologram, strictyaml
python-slugify==4.0.1     # via agate
pytimeparse==1.1.8        # via agate
pytz==2020.1              # via babel, google-api-core, snowflake-connector-python
pyyaml==5.3.1             # via dbt-core
requests==2.22.0          # via azure-storage-common, dbt-core, google-api-core, minimal-snowplow-tracker, snowflake-connector-python
rsa==4.6                  # via google-auth
ruamel.yaml.clib==0.2.0   # via -r requirements.in, ruamel.yaml
ruamel.yaml==0.16.10      # via -r requirements.in, strictyaml
s3transfer==0.3.3         # via boto3
six==1.15.0               # via -r requirements.in, agate, astroid, cryptography, dbt-bigquery, google-api-core, google-auth, google-cloud-bigquery, google-resumable-media, isodate, jsonschema, leather, minimal-snowplow-tracker, packaging, pip-tools, protobuf, pyopenssl, pyrsistent, python-dateutil
snowballstemmer==2.0.0    # via -r requirements.in, pydocstyle
snowflake-connector-python==2.2.1  # via dbt-snowflake
sqlparse==0.3.1           # via dbt-core
strictyaml==1.0.6         # via -r requirements.in
text-unidecode==1.3       # via python-slugify
toml==0.10.1              # via -r requirements.in, pylint
typed-ast==1.4.1          # via -r requirements.in, mypy
typing-extensions==3.7.4.2  # via -r requirements.in, dbt-core, mypy
urllib3==1.25.10          # via botocore, dbt-snowflake, requests, snowflake-connector-python
wcwidth==0.2.5            # via -r requirements.in, pytest
werkzeug==0.16.1          # via dbt-core
wrapt==1.12.1             # via -r requirements.in, astroid
zipp==3.1.0               # via -r requirements.in, importlib-metadata

# The following packages are considered to be unsafe in a requirements file:
# pip
# setuptools
```

I'd recommend creating a fresh virtualenv and going from there. For now, I'm going to close the issue; feel free to reopen if you uncover what's going on here.

**Closed by jtcohen6** 2020-07-31 14:17 UTC
Labels: bug

**Comment by TjrGithub** [comment] 2020-07-31 18:39
No, requirements.in contains only one line.

**Comment by TjrGithub** [comment] 2020-07-31 18:40
And it is a fresh virtualenv, created with python3 -m venv, activate, pip install --upgrade pip, pip install wheel, pip install -r requirements.txt from the above requirements.

**Comment by TjrGithub** [comment] 2020-07-31 18:59
I'm sorry - it does work in docker. Just not in my source repository. I agree this bug should be closed.

docker container run -it ubuntu:19.10 /bin/bash  -c 'apt-get update; apt-get install -y python3.7 python3-venv; /usr/bin/python3.7 -m venv venv ; . venv/bin/activate ; pip install --upgrade pip ; pip install wheel ; pip install pip-tools ; echo 'dbt' > requirements.in ; pip-compile requirements.in'
