### ISSUE TITLE
BigQuery Service Account JSON Authentication Failing

### ISSUE THREAD

**Issue by NdiranguMartin** [fishtown-analytics/dbt#2989] opened 2021-01-01 22:04 UTC
### Describe the bug
I have been previously using BigQuery's Service Account File Authentication to run DBT locally on my machine. However, the need to collaborate made me want to run it on a server using Service Account JSON Authentication. I followed the instructions to set up (using the `keyfile.json` to create `keyfile_json:` in my `profile.yml`) but I get the error both locally and on CI
```
Could not deserialize key data.
```

### Expected behavior
Successfully run DBT

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
Running with dbt=0.18.1
```

**The operating system you're using:** MacOS

**The output of `python --version`:** Python 2.7.17

**Comment by jtcohen6** [comment] 2021-01-02 18:01
Hey @NdiranguMartin, it's tricky to troubleshoot this without seeing your actual `profiles.yml` entry. As in #2553, it is definitely possible to use this authentication method for local development; the most likely cause of the bug here is that one of the nested attributes of `keyfile_json` is improperly formatted. The `private_key` is a frequent culprit. Be sure that you've copied all characters (including whitespace) exactly as they exist in `keyfile.json`.

I'm going to close this issue, since (a) it's a duplicate of #2553 and (b) it doesn't relate to a code change within dbt. That said, if there's something we can do to improve the specificity of the `Could not deserialize key data` error message, I'm definitely open to it.

**Closed by jtcohen6** 2021-01-02 18:01 UTC
Labels: bug, duplicate
