### ISSUE TITLE
Unable to install dbt and Airflow snowflake provider via Poetry

### ISSUE THREAD

**Issue by ahuynh3** [fishtown-analytics/dbt#3128] opened 2021-02-24 17:47 UTC
### Describe the feature
We are unable to install `dbt` and the Airflow snowflake provider via Poetry as we get the following error:
```
  SolverProblemError

  Because dbt-snowflake (0.19.1b2) depends on snowflake-connector-python[secure-local-storage] (2.3.6)
   and snowflake-connector-python[secure-local-storage] (2.3.6) depends on snowflake-connector-python (2.3.6), dbt-snowflake (0.19.1b2) requires snowflake-connector-python (2.3.6).
  And because apache-airflow[amazon,celery,crypto,ftp,hive,jdbc,mysql,password,postgresql,presto,sftp,slack,snowflake,ssh,statsd] (2.0.1) depends on snowflake-connector-python (>=2.3.8), dbt-snowflake (0.19.1b2) is incompatible with apache-airflow[amazon,celery,crypto,ftp,hive,jdbc,mysql,password,postgresql,presto,sftp,slack,snowflake,ssh,statsd] (2.0.1).
  So, because my-project depends on both apache-airflow[amazon,celery,crypto,ftp,hive,jdbc,mysql,password,postgresql,presto,sftp,slack,snowflake,ssh,statsd] (==2.0.1) and dbt-snowflake (0.19.1b2), version solving failed.
```

After digging deeper, `dbt-snowflake` pins the `snowflake-connector-python` package to version `2.3.6` (see [here](https://github.com/fishtown-analytics/dbt/blob/v0.19.1b2/plugins/snowflake/setup.py#L50)). Airflow constrains the `snowflake-connector-python` package version to `>=2.3.8` (see [here](https://github.com/apache/airflow/blob/2.0.1/setup.py#L434))

### Describe alternatives you've considered
I think we can fix this by not pinning the `snowflake-connector-python` version to 2.3.6 specifically, but setting the version constraint to `snowflake-connector-python>=2.3.6`. However we should ensure that things don't break with a newer version of the `snowflake-connector-python` and that the test suite still pass.

### Who will this benefit?
Anyone trying to install `dbt-snowflake` alongside the Airflow snowflake provider

**Comment by jtcohen6** [comment] 2021-02-25 08:57
Hey @ahuynh3, thanks for the detailed issue! We will definitely be upgrading our pin on `snowflake-connector-python` for the next minor version (v0.20.0), and that should resolve the stated issue. You can track the automated PR here: #3076.

> I think we can fix this by not pinning the `snowflake-connector-python` version to 2.3.6 specifically, but setting the version constraint to `snowflake-connector-python>=2.3.6`.

As it is, we're quite cautious with our requirement for snowflake-connector-python because it's a critical dependency for `dbt-snowflake`, because it in turn has a number of thorny dependencies, and because we've been burned once before (https://github.com/fishtown-analytics/dbt/issues/1892, caused by ahttps://github.com/snowflakedb/snowflake-connector-python/issues/225 + https://github.com/snowflakedb/snowflake-connector-python/issues/228). That said, I know the team behind snowflake-connector-python has been doing nontrivial work to rationalize their dependencies and better vendor their code. With each new minor version of dbt, we will be revisiting the pin and deciding whether to keep or loosen it.

I'm going to close this for now, as it's already planned work for v0.20.0.

**Closed by jtcohen6** 2021-02-25 08:57 UTC
Labels: dependencies, enhancement

**Comment by ahuynh3** [comment] 2021-02-25 17:59
Got it, thanks @jtcohen6 !
