### ISSUE TITLE
More informative error message when a package is not compatible with dbt's version

### ISSUE THREAD

**Issue by LePeti** [fishtown-analytics/dbt#2652] opened 2020-07-28 11:12 UTC
### Describe the feature

I'm using dbt v0.16.0 and when I've added dbt_utils v0.5.0 and ran `dbt deps` I received the following error message:

```
Encountered an error:
Runtime Error
  Failed to read package at /home/rdeployer/app/dbt_modules/dbt_utils: Runtime Error
    at path []: Additional properties are not allowed (‘config-version’ was unexpected)
```
The error occurred because dbt_utils' `dbt_project.yml` uses `config-version: 2` which isn't compatible with dbt v0.16.0.

I think an error message that clearly states that there is a version discrepancy would be helpful. Showing the version dependency on dbt Hub would also be helpful.

### Who will this benefit?

Anyone using dependencies.

**Comment by jtcohen6** [comment] 2020-07-28 14:30
@LePeti This is a great suggestion! I'm going to close the issue only because it's a duplicate of #2638. I'd encourage you to comment there if you have any additional thoughts, or if this is a change you're interested inn contributing.

**Closed by jtcohen6** 2020-07-28 14:30 UTC
Labels: duplicate, enhancement
