### ISSUE TITLE
DBT PostgreSQL not warning on indexes not getting created due to duplicate index name

### ISSUE THREAD

**Issue by sheyd** [fishtown-analytics/dbt#1945] opened 2019-11-21 15:55 UTC
My team uncovered a bug during our migration to DBT that involves index creation using post-hooks. 

Tech details:
* DBT Version: `0.14.3`
* Runtime environment: Ubuntu 16.04 using Python 3.7.5
* PostgreSQL version: 11.6 (running on Amazon RDS)

We were testing the code running in our production PostgreSQL database server in two different schemas to compare numbers. The `dbt_project.yml` model block is as follows:
```
event_log:
  event_log:
	alias: event_log
	materialized: table
	post-hook:
	  - "CREATE UNIQUE INDEX event_u_i ON {{ this }}(timestamp, user_id, event_id)"
  	  - "CREATE INDEX user_t ON {{ this }}(user_id, timestamp)"
```

We then had a cron job running the same job to 2 different schema's via different output profiles: `prod` and `test`.

The two commands we ran were:
`pipenv run dbt run -m event_log`
`pipenv run dbt run -m event_log --target test`

Both tables were created successfully, but only one had indexes created, since we were using specifically named indexes, and PostgreSQL, it appears, uses globally unique index names. DBT generated no warnings in the output for the tables whose indexes couldn't be created, even when ran with `warn-error` flag.

**Comment by mcgin** [comment] 2019-11-25 10:19
Seeing this behaviour on 14.4 too targeting postgres 11.5 on Google Cloud SQL

**Comment by drewbanin** [comment] 2019-11-25 16:33
This is really surprising - AFAIK, Postgres should return an error message like:
```
ERROR:  relation "event_u_i" already exists
```

instead of failing silently if the index already exists. You're definitely not running a hook that looks more like:
```
CREATE UNIQUE INDEX IF NOT EXISTS event_u_i ON {{ this }}(timestamp, user_id, event_id)
```

right? That would likely result in the behavior that you're seeing here.

We can definitely look further into this, but in the meantime, it's probably a good idea to prefix the index name with the schema and alias of the model, eg:
```
CREATE UNIQUE INDEX {{ this.schema }}__{{ this.name }}_u_i ON {{ this }}(timestamp, user_id, event_id)
```

This will ensure that index names are unique across schemas.

**Comment by danielerapati** [comment] 2020-01-21 14:47
Hi,
I'm getting a similar problem when targeting postgres and using the [postgres.index](https://github.com/fishtown-analytics/postgres/blob/master/macros/optimizers/index.sql) macro in a `post-hook`. After the first `dbt run` the indexes are created as expected. After the second `dbt run` the indexes disappear and reappear after the third.
I think what is happening is that `CREATE INDEX IF NOT EXISTS` looks up the index by name and, inside the transaction, an index with that name is still present on the "backup" table created here:
https://github.com/fishtown-analytics/dbt/blob/dev/0.15.1/core/dbt/include/global_project/macros/materializations/table/table.sql#L45
A work-around: put index creation inside an `after_commit` or specify `transaction=False` (see [using hooks to vacuum](https://docs.getdbt.com/docs/hooks#section-using-hooks-to-vacuum)).
The problem is deeply connected to how table materialization uses the backup table: a solution could be to override the table materialization in the postgres plugin and, just for postgres, rely only on transaction rollback without a backup table.

**Comment by drewbanin** [comment] 2020-01-21 18:53
Hey @danielerapati - this is a really great insight! It's not something that I had considered before, and it makes a lot of sense.

I think that either one of:
1. moving the post-hook to run outside of the transaction, or
2. adding a suffix to the index name (eg. based on the start time of the run, accessible via `run_started_at.strftime("%s")`)

would make this work well. My instinct is that this index should be created inside of the transaction, otherwise external queriers might hit the table without the index being present

**Comment by drewbanin** [comment] 2020-02-21 23:08
I am closing this issue with the #wontfix label and re-opening #804 to track the feature request for first-class support of indexes in Postgres.

**Closed by drewbanin** 2020-02-21 23:08 UTC
Labels: redshift/pg, wontfix
