### ISSUE TITLE
Feature Request: --fail-fast argument for dbt run and dbt test

### ISSUE THREAD

**Issue by JasonGluck** [fishtown-analytics/dbt#1649] opened 2019-07-31 17:38 UTC
## Feature
`--fail-fast` argument for `dbt run` and `dbt test`

### Feature description
An optional argument, `--fail-fast`, for dbt run and dbt test which will stop model builds or test runs upon a single failure. It may also be worth adding a parameter which will define the amount of failures to allow before stopping.

### Who will this benefit?
All dbt users. Will be useful during the development process. Can also help reduce the amount of queries to the database.

### Questions
How should this work with test severity?

**Comment by drewbanin** [comment] 2019-07-31 19:16
Thanks @JasonGluck! I think we might have built this at a hackathon once, but I don't think the code ever made it into prod :/

I think the operative line of code is [right here](https://github.com/fishtown-analytics/dbt/blob/7177a6543b56d5d90446710e7295aaebeb415092/core/dbt/task/runnable.py#L113). I imagine we could add some logic there which consulted the value of the `--fail-fast` flag. If `--fail-fast` is provided, then dbt should "raise" regardless of the value supplied in `raise_on_first_error()`.

Is this something you'd be interested in contributing a PR for?

**Comment by drewbanin** [comment] 2019-08-06 14:28
Dupe of #871 - closing that one.

**Comment by jars** [comment] 2019-09-10 19:48
This would save our team a lot of time!

**Comment by Raalsky** [comment] 2020-03-15 12:39
I'm currently thinking about the behavior of `GraphRunnableTask.call_runner` in case of `dbt test` and modifying it with `fail-fast` based on discussion in #1675 (and setting `self._raise_next_tick` based on `result.fail`). Let me know if I'm wrong with that but it seems that during testing the `job_queue` structure is flat (as expected) with no dependents between nodes. But if we're waiting for `self._raise_next_tick` to be considered (throw `_raise_set_error()`) it will be [called only during submitting tasks to threads pool](https://github.com/fishtown-analytics/dbt/blob/b77b3a45661e68a647a6be91e197c1cd13545982/core/dbt/task/runnable.py#L211) (before of tests execution) and [after the end of all tasks (tests) execution in](https://github.com/fishtown-analytics/dbt/blob/b77b3a45661e68a647a6be91e197c1cd13545982/core/dbt/task/runnable.py#L224). So we currently changing nothing than disabling summary list after the execution.

Now I'm looking for place where we can gentle raise in-between testing. Of course I really appreciate any help with that 🍺 

My current state of work could be found at: [raalsky/fail-fast](https://github.com/fishtown-analytics/dbt/compare/dev/octavius-catto...Raalsky:fail-fast)

I'm also thinking about testing these parts of codebase in some sort of providing a desired list of nodes to `job_queue` (which is really brutal in some sense 🌵 ).

Of course If @sjwhitworth is still working on it just let me know 😉

**Comment by drewbanin** [comment] 2020-03-18 19:03
hey @Raalsky - this is a really good point! Tagging @beckjake to advise -- I'm definitely seeing the behavior you're describing when I run your branch locally :)

Jake, what's the best way to bubble up test failures to fail-fast? Or, should we consider how we feed test nodes into the runner?

**Comment by beckjake** [comment] 2020-03-18 19:19
What a great point! That's definitely a hole in the process. I think the key issue is using `job_queue.join()` which ultimately does this on a `queue.PriorityQueue`:
```
with self.all_tasks_done:
    while self.unfinished_tasks:
        self.all_tasks_done.wait()
```

We could do this (but probably abstract it so we aren't reaching so far into internals):
```
with self.job_queue.inner.all_tasks_done:
    while self.job_queue.inner.unfinished_tasks:
        self._raise_next_tick()
        self.job_queue.inner.all_tasks_done.wait()
```


I would probably do that by writing a `join_with(self, func)` method inside the graph queue code and calling it like `self.job_queue.join_with(self._raise_next_tick)`. It's going to be a bit messy no matter what, I suspect.

**Comment by Raalsky** [comment] 2020-03-18 21:25
Hi @drewbanin and @beckjake
I much appreciate your suggestions 🚀 . I'll be back in a few days with updates.

**Comment by Raalsky** [comment] 2020-03-19 12:22
@beckjake 
Based on implementation of `PriorityQueue` (`Queue`) I think the reformat of `job_queue.join()` might be insufficient. In the following:
```python
with self.job_queue.inner.all_tasks_done:
    while self.job_queue.inner.unfinished_tasks:
        tell_the_world_is_ending()
        self.job_queue.inner.all_tasks_done.wait()
```
I think the `tell_the_world_is_ending()` will be called only once during `dbt test`. The reason is located in implementation of `job_queue.task_done()` which is called at the end of execution of every task (test):
```python
    def task_done(self):
        '''Indicate that a formerly enqueued task is complete.

        Used by Queue consumer threads.  For each get() used to fetch a task,
        a subsequent call to task_done() tells the queue that the processing
        on the task is complete.

        If a join() is currently blocking, it will resume when all items
        have been processed (meaning that a task_done() call was received
        for every item that had been put() into the queue).

        Raises a ValueError if called more times than there were items
        placed in the queue.
        '''
        with self.all_tasks_done:
            unfinished = self.unfinished_tasks - 1
            if unfinished <= 0:
                if unfinished < 0:
                    raise ValueError('task_done() called too many times')
                self.all_tasks_done.notify_all()
            self.unfinished_tasks = unfinished
```
We're blocking on `self.job_queue.inner.all_tasks_done.wait()` which will be called by `task_done()` throw `self.all_tasks_done.notify_all()` (as it's simple Mutex) only when there is noting to process actually (so basically after the end of all tests execution).

I think we should consider also rewrite of `task_done()` with some mechanism of `notify_after_something_was_done` in addition to `.join()`.
OR
Mixing the task submitting part with some sort of wait (maybe based on number of threads). Of course it's only direction:
```python
        while nothing_to_be_processed:
            node = self.job_queue.get()
            self._raise_set_error()
            runner = self.get_runner(node)
            ...
            self._submit(pool, args, callback)
            # Only an approximation of queue size!
            if self.job_queue.qsize() >= self.config.threads:
                 self.job_queue.wait_until_something_was_done()
```

**Comment by Raalsky** [comment] 2020-03-19 12:28
Keep in mind it's not only about `dbt test` but also in `dbt run` when we have a bunch of independent tasks (aka. large "layer") for example transforming sources etc.

**Comment by Raalsky** [comment] 2020-03-19 15:54
I've pushed an MVP to [Raalsky/fail-fast](https://github.com/fishtown-analytics/dbt/compare/dev/octavius-catto...Raalsky:fail-fast) (need a lot in carrying about concurrency 😭 ) but it works pretty close to what I've expected.

**Comment by beckjake** [comment] 2020-03-19 17:43
Oh, I didn't realize that `task_done` only calls `notify_all` when there are no unfinished tasks, I thought it was every time. That's a bummer! I looked through your branch and I like your changes, that seems like a solid solution.

**Closed** 2020-03-24 14:36 UTC
Labels: enhancement, good first issue
