### ISSUE TITLE
dbt model run fails silently when `--bypass-cache` is used

### ISSUE THREAD

**Issue by darthburrito** [fishtown-analytics/dbt#1448] opened 2019-05-08 22:19 UTC
## Issue
dbt model run fails silently when `--bypass-cache` is used
### Issue description

To bypass an issue with sources fixed by this [PR](https://github.com/fishtown-analytics/dbt/pull/1442). we deployed our models by using `dbt run --bypass-cache`. 
the runs were marked as completed without reporting any errors but on querying the models we notice that data was not being refreshed. 
On further investigation we noticed that dbt issues a `ROLLBACK` on the same connection before `COMMIT` after a successful model deploy.

```
2019-05-08 06:02:53,109 (Thread-2): On cf_trackerv2_action_logs: 
       delete
  from "mango"."dbt"."cf_trackerv2_action_logs"
  where (my_key) in (
    select (mykey)
    from "cf_trackerv2_action_logs__dbt_incremental_tmp"
  );
       insert into "mango"."dbt"."cf_trackerv2_action_logs" ("data", "mykey")
       (
         select 
              "data","mykey"
         from "cf_trackerv2_action_logs__dbt_incremental_tmp"
       );
2019-05-08 06:03:04,851 (Thread-2): SQL status: INSERT 0 50294 in 11.74 seconds
2019-05-08 06:03:04,865 (Thread-2): Using redshift connection "cf_trackerv2_action_logs".
2019-05-08 06:03:04,865 (Thread-2): On cf_trackerv2_action_logs: select
      'mango' as database,
      tablename as name,
      schemaname as schema,
      'table' as type
    from pg_tables
    where schemaname ilike 'dbt'
    union all
    select
      'mango' as database,
      viewname as name,
      schemaname as schema,
      'view' as type
    from pg_views
    where schemaname ilike 'dbt'
2019-05-08 06:03:09,893 (Thread-2): SQL status: SELECT in 5.03 seconds
2019-05-08 06:03:09,900 (Thread-2): On cf_trackerv2_action_logs: ROLLBACK
2019-05-08 06:11:55,350 (Thread-2): 06:11:55 | 2 of 169 OK created incremental model dbt.cf_trackerv2_action_logs... [INSERT 0 50294 in 583.98s]
```
 
### Results
```
2019-05-08 06:02:53,105 (Thread-2): SQL status: SELECT in 4.32 seconds
2019-05-08 06:02:53,108 (Thread-2): Writing runtime SQL for node "model.sherlock.cf_trackerv2_action_logs"
2019-05-08 06:02:53,109 (Thread-2): Using redshift connection "cf_trackerv2_action_logs".
2019-05-08 06:02:53,109 (Thread-2): On cf_trackerv2_action_logs: 
       delete
  from "mango"."dbt"."cf_trackerv2_action_logs"
  where (my_key) in (
    select (mykey)
    from "cf_trackerv2_action_logs__dbt_incremental_tmp"
  );
       insert into "mango"."dbt"."cf_trackerv2_action_logs" ("data", "mykey")
       (
         select 
              "data","mykey"
         from "cf_trackerv2_action_logs__dbt_incremental_tmp"
       );
2019-05-08 06:03:04,851 (Thread-2): SQL status: INSERT 0 50294 in 11.74 seconds
2019-05-08 06:03:04,854 (Thread-2): Using redshift connection "cf_trackerv2_action_logs".
2019-05-08 06:03:04,854 (Thread-2): On cf_trackerv2_action_logs: 
      GRANT SELECT ON "mango"."dbt"."cf_trackerv2_action_logs" TO GROUP mango
2019-05-08 06:03:04,856 (Thread-2): SQL status: GRANT in 0.00 seconds
2019-05-08 06:03:04,858 (Thread-2): Using redshift connection "cf_trackerv2_action_logs".
2019-05-08 06:03:04,858 (Thread-2): On cf_trackerv2_action_logs: 
      GRANT SELECT ON "mango"."dbt"."cf_trackerv2_action_logs" TO GROUP SUPERSET
2019-05-08 06:03:04,859 (Thread-2): SQL status: GRANT in 0.00 seconds
2019-05-08 06:03:04,865 (Thread-2): Using redshift connection "cf_trackerv2_action_logs".
2019-05-08 06:03:04,865 (Thread-2): On cf_trackerv2_action_logs: select
      'mango' as database,
      tablename as name,
      schemaname as schema,
      'table' as type
    from pg_tables
    where schemaname ilike 'dbt'
    union all
    select
      'mango' as database,
      viewname as name,
      schemaname as schema,
      'view' as type
    from pg_views
    where schemaname ilike 'dbt'
2019-05-08 06:03:09,893 (Thread-2): SQL status: SELECT in 5.03 seconds
2019-05-08 06:03:09,900 (Thread-2): On cf_trackerv2_action_logs: ROLLBACK
2019-05-08 06:03:12,091 (Thread-2): Acquiring new redshift connection "cf_trackerv2_action_logs".
2019-05-08 06:03:12,091 (Thread-2): Re-using an available connection from the pool.
2019-05-08 06:03:12,091 (Thread-2): Using redshift connection "cf_trackerv2_action_logs".
2019-05-08 06:03:12,091 (Thread-2): On cf_trackerv2_action_logs: BEGIN
2019-05-08 06:03:12,094 (Thread-2): SQL status: BEGIN in 0.00 seconds
2019-05-08 06:03:12,095 (Thread-2): Using redshift connection "cf_trackerv2_action_logs".
2019-05-08 06:03:12,095 (Thread-2): On cf_trackerv2_action_logs: 
  insert into dbt.dbt_model_log(
    event_name,
    event_timestamp,
    schema,
    model,
    materialization,
    invocation_id,
    row_count
    )
  values (
    'MODEL_END',
    current_timestamp,
    'dbt',
    'cf_trackerv2_action_logs',
    'incremental',
    '779c340c-4a5c-4186-ae16-904cf06bfe05',
     (select count(1) from "mango"."dbt"."cf_trackerv2_action_logs")::bigint
    )
2019-05-08 06:11:52,919 (Thread-2): SQL status: INSERT 0 1 in 520.82 seconds
2019-05-08 06:11:52,933 (Thread-2): Using redshift connection "cf_trackerv2_action_logs".
2019-05-08 06:11:52,933 (Thread-2): On cf_trackerv2_action_logs: select
      'mango' as database,
      tablename as name,
      schemaname as schema,
      'table' as type
    from pg_tables
    where schemaname ilike 'dbt'
    union all
    select
      'mango' as database,
      viewname as name,
      schemaname as schema,
      'view' as type
    from pg_views
    where schemaname ilike 'dbt'
2019-05-08 06:11:54,710 (Thread-2): SQL status: SELECT in 1.78 seconds
2019-05-08 06:11:54,717 (Thread-2): On cf_trackerv2_action_logs: ROLLBACK
2019-05-08 06:11:54,884 (Thread-2): Skipping compression on: "mango"."dbt"."cf_trackerv2_action_logs"
2019-05-08 06:11:54,884 (Thread-2): Acquiring new redshift connection "cf_trackerv2_action_logs".
2019-05-08 06:11:54,884 (Thread-2): Re-using an available connection from the pool.
2019-05-08 06:11:54,885 (Thread-2): Using redshift connection "cf_trackerv2_action_logs".
2019-05-08 06:11:54,885 (Thread-2): On cf_trackerv2_action_logs: BEGIN
2019-05-08 06:11:54,888 (Thread-2): SQL status: BEGIN in 0.00 seconds
2019-05-08 06:11:54,888 (Thread-2): Using redshift connection "cf_trackerv2_action_logs".
2019-05-08 06:11:54,888 (Thread-2): On cf_trackerv2_action_logs: 
    select 1; -- suppress 'can't execute empty query'
2019-05-08 06:11:54,890 (Thread-2): SQL status: SELECT in 0.00 seconds
2019-05-08 06:11:54,892 (Thread-2): Using redshift connection "cf_trackerv2_action_logs".
2019-05-08 06:11:54,892 (Thread-2): On cf_trackerv2_action_logs: 
      grant select on "mango"."dbt"."cf_trackerv2_action_logs" to looker_dbt
2019-05-08 06:11:54,895 (Thread-2): SQL status: GRANT in 0.00 seconds
2019-05-08 06:11:54,897 (Thread-2): Using redshift connection "cf_trackerv2_action_logs".
2019-05-08 06:11:54,897 (Thread-2): On cf_trackerv2_action_logs: 
      grant select on "mango"."dbt"."cf_trackerv2_action_logs" to group mango
2019-05-08 06:11:54,899 (Thread-2): SQL status: GRANT in 0.00 seconds
2019-05-08 06:11:54,901 (Thread-2): Using redshift connection "cf_trackerv2_action_logs".
2019-05-08 06:11:54,901 (Thread-2): On cf_trackerv2_action_logs: 
      grant select on "mango"."dbt"."cf_trackerv2_action_logs" to superset
2019-05-08 06:11:54,904 (Thread-2): SQL status: GRANT in 0.00 seconds
2019-05-08 06:11:54,905 (Thread-2): On cf_trackerv2_action_logs: COMMIT
2019-05-08 06:11:54,905 (Thread-2): Using redshift connection "cf_trackerv2_action_logs".
2019-05-08 06:11:54,905 (Thread-2): On cf_trackerv2_action_logs: COMMIT
2019-05-08 06:11:55,346 (Thread-2): SQL status: COMMIT in 0.44 seconds
2019-05-08 06:11:55,350 (Thread-2): 06:11:55 | 2 of 169 OK created incremental model dbt.cf_trackerv2_action_logs... [INSERT 0 50294 in 583.98s]
```

### System information
The output of `dbt --version`:
```
installed version: 0.13.0
   latest version: 0.13.0

Up to date!
```
The operating system you're running on:
amazon linux
The python version you're using (probably the output of `python --version`)
`Python 2.7.14`
### Steps to reproduce
- `dbt run  --bypass-cache`
-  some incremental models are marked as completed but incremental data is missing

**Comment by drewbanin** [comment] 2019-05-08 22:22
Thanks for the report @darthburrito! @beckjake you indicated that this should be fixed in 0.14.0 (unreleased), right? I'll verify and then close out this ticket if everything is working as expected

**Comment by beckjake** [comment] 2019-05-09 01:35
Yeah, it's fixed in `dev/wilt-chamberlain`, which I verified locally to my satisfaction. I'm pretty sure the issue is around us "releasing" the connection after we call `list_relations_without_caching`. We should not do that, except sometimes when we have to, which is why it's fixed in `dev/wilt-chamberlain` where we finally cleaned up connection/transaction management quite a bit.

**Comment by drewbanin** [comment] 2019-05-09 12:01
@beckjake roger! Closing this one :)

**Closed by drewbanin** 2019-05-09 12:01 UTC
Labels: bug
