### ISSUE TITLE
Error when upgrading dbt

### ISSUE THREAD

**Issue by hoanghapham** [fishtown-analytics/dbt#1225] opened 2019-01-09 03:03 UTC
### Issue description
When I ran ```pip install dbt --upgrade``` on fish, the comman ran for a while and stopped with this error:

> "pip install dbt --upgrade” terminated by signal SIGSEGV (Address boundary error)

However ```pip3 install dbt --upgrade``` works fine.

### System information

- dbt version: should be **0.12.2a1** because I first installed dbt on Jan 3rd
- Operating system: Ubuntu 18.04.1 LTS
- Python version: Python 2.7.15rc1
- Shell: fish

**Comment by drewbanin** [comment] 2019-01-09 03:16
Thanks for the report @hoanghapham! It's super difficult to pin down bugs like this, and I'm unfortunately not able to reproduce it on my machine.

The fact that `pip3` works but `pip` (using python2) does not makes me think that your version of Python might be relevant. In particular, I wonder if there's some sort of issue with 2.7.15rc1. I poked around in some of the [changelogs](https://github.com/python/cpython/tree/2.7/Misc/NEWS.d), but couldn't find anything that sounded like a possible culprit.

If I'm understanding this correctly, it sounds to me like the error is coming from `pip` and not from `dbt`, so I'm actually unsure how likely it is that this problem is caused by dbt itself. More likely, I think it probably has to do with one of the modules that dbt imports. We rely on different modules for each warehouse that dbt connects to, and in my experience, bugs like this tend to come from libs written in C (like pyOpenSSL, pyscopg2, etc).

**Comment by hoanghapham** [comment] 2019-01-09 04:57
@drewbanin  I uninstalled dbt and tried to reinstall the old package with ```pip install dbt==0.12.2rc1```. After collecting packages it failed to install and this is the final message:

```
Installing collected packages: functools32, jsonschema, jmespath, docutils, six, python-dateutil, botocore, urllib3, certifi, chardet, idna, requests, minimal-snowplow-tracker, psycopg2, decorator, networkx, PyYAML, future, parsedatetime, leather, pytimeparse, Unidecode, python-slugify, pytz, Babel, isodate, agate, cachetools, pyasn1, pyasn1-modules, rsa, google-auth, setuptools, protobuf, futures, googleapis-common-protos, google-api-core, google-cloud-core, google-resumable-media, google-cloud-bigquery, MarkupSafe, Jinja2, s3transfer, boto3, colorama, sqlparse, azure-nspkg, azure-common, enum34, asn1crypto, pycparser, cffi, ipaddress, cryptography, pycryptodomex, pyjwt, pyOpenSSL, ijson, azure-storage-nspkg, azure-storage-common, azure-storage-blob, snowflake-connector-python, dbt
fish: “pip install dbt==0.12.2rc1” terminated by signal SIGSEGV (Address boundary error)
```
if I switch to bash this will be the final line:

```Segmentation fault (core dumped)```

Now when I try pip3 it also doesn't work:

```fish: “pip3 install dbt==0.12.2rc1” terminated by signal SIGSEGV (Address boundary error)```

Trying to install the latest version with ```pip install dbt```  or ```pip3 install dbt```  also doesn't work 
Pip / Pip3 crashed and this is a part of the report generated by Ubuntu:

![screenshot from 2019-01-09 11-48-00](https://user-images.githubusercontent.com/13628076/50877656-72819e00-1405-11e9-8a36-79ff7ff83c9a.png)

**Comment by drewbanin** [comment] 2019-01-09 14:46
@hoanghapham thanks for the update! Glad to hear it worked after upgrading pip. I'm really stumped as to why this would happen, but I'll definitely keep it in mind if I hear of similar reports in the future. I'm going to close this issue since it doesn't sound like any immediate action is required in dbt, but thanks again for giving us a head up.

**Closed by drewbanin** 2019-01-09 14:46 UTC
Labels: more information needed

**Comment by hoanghapham** [comment] 2019-01-10 02:01
No problem. Thanks for the great tool @drewbanin, keep up the good work.
