### ISSUE TITLE
Host v1.json from schema

### ISSUE THREAD

**Issue by joshuataylor** [fishtown-analytics/dbt#2872] opened 2020-11-07 15:25 UTC
### Describe the feature
On https://github.com/fishtown-analytics/dbt/issues/2670 it was outlined that there would be a  schema hosted at `https://schemas.getdbt.com/dbt/manifest/v1.json`.

### Describe alternatives you've considered
Host the spec locally?

### Additional context
I am creating a language server implementation and also a VSCode extension for dbt, and reading this is one of the steps I am performing to provide a consistent user experience. I can then know that if dbt suddenly comes out with v2 or 1.1 or whatever, I can just update according to the spec.

### Who will this benefit?
Plugin authors, schema creation, etc :)?

### Are you interested in contributing this feature?
Yes!

**Comment by jtcohen6** [comment] 2020-11-08 16:48
Hey @joshuataylor, I totally agree, this is something we plan to do! Check out #2870. I'm going to close this issue only because it's a duplicate of that one.

In the future, we may want to host schemas of dbt classes and context methods, in addition to the artifacts it produces. The goal would be to enable extension maintainers to provide even richer tooling (snippets, autocompletion, descriptions) in development environments.

**Closed by jtcohen6** 2020-11-08 16:48 UTC
Labels: duplicate, enhancement
