### ISSUE TITLE
dbt model run fails silently on Windows

### ISSUE THREAD

**Issue by danielbcook** [fishtown-analytics/dbt#1604] opened 2019-07-11 23:03 UTC
Please make sure to fill out either the issue template or the feature template and delete the other one!

### Issue description
I've got 4 models, all with `materialized='incremental'` at the top of their model definition and each model / view receives a fairly constant flow of new rows. Sometimes when I run dbt no rows are up/serted (which doesn't make sense), but if I immediately turn around and re-run dbt I get the expected # of upserts.

### Results
Nothing on the first run, but in 100% of repro cases a second run immediately afterward behaves as expected. 

Appended here are some example results when running in the CLI. Note that the first run does nothing, but re-running is more productive.

> PS > dbt run
> Running with dbt=0.14.0
> Found 4 models, 0 tests, 0 snapshots, 0 analyses, 117 macros, 0 operations, 0 seed files, 0 sources
> 
> 14:19:36 | Concurrency: 5 threads (target='dev')
> 14:19:36 |
> 14:19:36 | 1 of 4 START incremental model public.anonymous_user_mappings........ [RUN]
> 14:19:36 | 2 of 4 START incremental model public.earliest_user_events........... [RUN]
> 14:19:36 | 3 of 4 START incremental model public.real_time_utm.................. [RUN]
> 14:19:36 | 4 of 4 START incremental model public.unified_user_id................ [RUN]
> PS > dbt run
> Running with dbt=0.14.0
> Found 4 models, 0 tests, 0 snapshots, 0 analyses, 117 macros, 0 operations, 0 seed files, 0 sources
> 
> 14:19:47 | Concurrency: 5 threads (target='dev')
> 14:19:47 |
> 14:19:47 | 1 of 4 START incremental model public.anonymous_user_mappings........ [RUN]
> 14:19:47 | 2 of 4 START incremental model public.earliest_user_events........... [RUN]
> 14:19:47 | 3 of 4 START incremental model public.real_time_utm.................. [RUN]
> 14:19:47 | 4 of 4 START incremental model public.unified_user_id................ [RUN]
> 14:19:48 | 4 of 4 OK created incremental model public.unified_user_id........... [INSERT 0 743 in 0.49s]
> 14:19:48 | 2 of 4 OK created incremental model public.earliest_user_events...... [INSERT 0 111 in 0.51s]
> 14:19:48 | 1 of 4 OK created incremental model public.anonymous_user_mappings... [INSERT 0 19 in 0.97s]
> 14:19:50 | 3 of 4 OK created incremental model public.real_time_utm............. [INSERT 0 57 in 2.62s]
> 14:19:50 |
> 14:19:50 | Finished running 4 incremental models in 3.51s.
> 
> Completed successfully
> 
> Done. PASS=4 ERROR=0 SKIP=0 TOTAL=4
> 

### System information
installed version: 0.14.0
   latest version: 0.14.0

The operating system you're running on: (Windows 64-bit)
OS Version:                10.0.17763 N/A Build 17763
OS Build Type:             Multiprocessor Free

The python version you're using: Python 3.7.3

### Steps to reproduce
1. pip to upgrade to 0.14, which makes me suspect I used it to install initially too.
2. Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
3. psycopg2 = 2.7.7 (dt dec pq3 ext lo64)

### Log file results
See attached: https://gist.github.com/drewbanin/5898a683bf32587134764a2ed9b96768

Edit: @drewbanin moved debug log output to a gist

**Comment by drewbanin** [comment] 2019-07-14 17:48
Hey @danielbcook - thanks for making this report. I tried to reproduce this, but wasn't able to do so on my hardware. Was this a one-time issue, or does it happen frequently! And if it happens frequently: is there any sort of pattern or commonality you can determine when dbt fails this way?

**Comment by danielbcook** [comment] 2019-07-15 17:20
I do still see the issue happening. I previously thought that the problem was limited to incremental runs but I have now observed it happening during a full refresh.

I have not observed an obvious pattern to the issue. The machine that it normally runs on hovers at about 15% CPU utilization so I don’t think it’s CPU-limited, but maybe it is RAM-limited (that’s currently at 70%)

**Comment by drewbanin** [comment] 2019-07-15 17:27
Huh, that's interesting - I'd be very surprised if it was related to an out of memory issue. My instinct is that Python would exit with an exception if that was the case.

The next time this fails, can you try checking dbt's exit code? I'm not a Windows expert - I'm unsure if you want `$?` or `$LastExitCode`, but basically, I'd be very curious to know what kind of state dbt exits in.

**Comment by danielbcook** [comment] 2019-07-15 17:33
Normally $LastExitCode returns a value of 0 and $? returns a value of true.

When the silent fail happens, $LastExitCode returns a value of -1073740940 and $? returns a value of false.

**Comment by drewbanin** [comment] 2019-07-15 17:43
Ok, that's something!! I believe `-1073740940` means [STATUS_HEAP_CORRUPTION](https://social.microsoft.com/Forums/en-US/6237ab2f-a4c3-47ea-9e90-652dc63081fd/exit-code-1073740940?forum=windowshpcdevs).

So, it sounds like one of dbt's dependencies is doing something bad in memory which leads to this error. My best guess is that this is coming from `psycopg2` (which dbt uses to run queries against Postgres) but I can't see anything in the psycopg2 release notes about heap corruption errors...

Sounds like the next step here is going to be to pinpoint where dbt is when this failure occurs. My instinct is that dbt is trying to run a `BEGIN` query, but it's hard to tell exactly what dbt is doing from the logs you've sent over.

Can you try running dbt in `--single-threaded` mode? That should help rule out dbt's multi-processing code as the culprit here. You should be able to run:
```
dbt --single-threaded run
```

**Comment by danielbcook** [comment] 2019-07-15 17:53
It seems that running in single-thread mode doesn’t exhibit the problem behavior. I just ran about 20 consecutive times, which normally would fail at least once. Here is the typical result set:

PS > dbt --single-threaded run
Running with dbt=0.14.0
Found 5 models, 0 tests, 0 snapshots, 0 analyses, 117 macros, 0 operations, 0 seed files, 0 sources

10:50:12 | Concurrency: 5 threads (target='dev')
10:50:12 |
10:50:12 | 1 of 5 START incremental model public.anonymous_user_mappings........ [RUN]
10:50:12 | 1 of 5 OK created incremental model public.anonymous_user_mappings... [INSERT 0 0 in 0.46s]
10:50:12 | 2 of 5 START incremental model public.earliest_user_events........... [RUN]
10:50:13 | 2 of 5 OK created incremental model public.earliest_user_events...... [INSERT 0 0 in 0.21s]
10:50:13 | 3 of 5 START incremental model public.platform_events................ [RUN]
10:50:14 | 3 of 5 OK created incremental model public.platform_events........... [INSERT 0 1 in 0.19s]
10:50:14 | 4 of 5 START incremental model public.real_time_utm.................. [RUN]
10:50:16 | 4 of 5 OK created incremental model public.real_time_utm............. [INSERT 0 1 in 2.02s]
10:50:16 | 5 of 5 START incremental model public.unique_ip_address.............. [RUN]
10:50:17 | 5 of 5 OK created incremental model public.unique_ip_address......... [INSERT 0 0 in 0.31s]
10:50:17 |
10:50:17 | Finished running 5 incremental models in 5.29s.

Completed successfully

**Comment by drewbanin** [comment] 2019-07-15 18:12
Got it! So, my guess is that this is related to `psycopg2` issues with `ssl` when multi-threading is enabled. We think this issue in particular looks relevant: https://github.com/psycopg/psycopg2-wheels/pull/8#issuecomment-480941411

If we make a branch that uses a more recent version of psycopg2 which addresses this bug, would you be interested in helping us test it out?

**Comment by danielbcook** [comment] 2019-07-15 18:14
Sure. Would it just involve replacing the psycopg2 binary?

**Comment by drewbanin** [comment] 2019-07-15 18:17
Yeah! If you're able, the easiest way to test this is to just run  `pip uninstall psycopg2 && pip install psycopg2-binary` in your Python environment.

That's going to be easier than installing from a branch. If that works for you, then we can figure out a way to get dbt to use this binary for a future release.

**Comment by danielbcook** [comment] 2019-07-15 19:16
So far no silent fails with the new binary

**Comment by drewbanin** [comment] 2019-07-15 19:23
Cool, thanks for the heads up @danielbcook.

I'm going to close this issue in favor of https://github.com/fishtown-analytics/dbt/issues/1221 (which I'll prioritize accordingly).

By all accounts, it sounds like `psycopg2-binary` isn't intended for use in libraries, so we're going to need to have a discussion around how exactly we should proceed.

In sum (and for posterity): One or more issues with psycopg2 < 2.8.2 (https://github.com/psycopg/psycopg2/issues/543, https://github.com/psycopg/psycopg2/issues/836) cause dbt runs against Postgres on Windows to crash silently with a `STATUS_HEAP_CORRUPTION` exit code. This specifically happens when dbt is run with multiple threads, apparently because the relevant ssl isn't initialized corrected for multi-threaded use.

You indicated that you're using Postgres on GCP: I'm not certain that this is relevant, but I will say: I haven't seen anyone else report this issue on Windows with postgres/Redshift, so we can't exactly rule it out.

Thanks for your help in debugging @danielbcook - we really appreciate it!

**Closed by drewbanin** 2019-07-15 19:23 UTC
Labels: bug, help wanted, windows

**Comment by danielbcook** [comment] 2019-07-24 15:47
Update: when running `dbt` on a Windows Server 2016 machine, and unlike the behavior on my Windows 10 laptop, Python crashes with a system modal dialog saying "Python Has Stopped Working". The event log showed the following (prior to upgrading psycopg2):

```
Faulting application name: python.exe, version: 3.7.2150.1013, time stamp: 0x5c2015ea
Faulting module name: ntdll.dll, version: 10.0.14393.2969, time stamp: 0x5ccd148a
Exception code: 0xc0000374
Fault offset: 0x00000000000f7b43
Faulting process id: 0x31c8
Faulting application start time: 0x01d541d9b873556a
Faulting application path: c:\program files\python\python.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: 62f6d265-ce24-46a3-a6aa-0f526fc3a7f9
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by drewbanin** [comment] 2019-07-24 15:58
Thanks @danielbcook - that's still not great, but good to know that the root cause of this was indeed a OS-level heap issue.

Looking forward to merging in #1221!
