### ISSUE TITLE
builtins.ref.database returning full statement code for CTE's

### ISSUE THREAD

**Issue by ciejer** [fishtown-analytics/dbt#2631] opened 2020-07-16 23:24 UTC
### Describe the bug
The statement `{{- builtins.ref('dbt_run_results_stage').database -}}` returns the CTE SQL `with __DBT__CTE__... as (...` statement before returning 'None' database, when queried for ephemeral objects.

### Steps To Reproduce

1. Create an ephemeral model in DBT
2. Reference this model with a `{{- builtins.ref('<ephemeral model name>').database -}}` statement

### Expected behavior
This snippet should return the name of the database the ephemeral model is executed on.

### Screenshots and log output
![image](https://user-images.githubusercontent.com/5128505/87731803-70c93f80-c81f-11ea-820e-d43911572534.png)

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [-] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
DBT Cloud - 0.16.1

**The operating system you're using:**
DBT Cloud

**The output of `python --version`:**

**Comment by jtcohen6** [comment] 2020-07-17 14:46
Hey @ciejer, thanks for the writeup. This isn't a bug per se; it's actually the intended behavior. Here's the idea:

* Any time you `ref()` an ephemeral model, dbt will interpolate its compiled model SQL as a CTE at the top of the file. For instance, if you put `-- depends on: {{ ref('my_ephemeral_model') }}` in your model file, dbt will include its compiled SQL in a CTE at the top of the file, even if you proceed to never select from it.

* An ephemeral model named `my_ephemeral_model` will be created as a dbt [relation](https://docs.getdbt.com/reference/dbt-classes/#relation) with `Path(database=None, schema=None, identifier='__dbt__CTE__my_ephemeral_model')`. (See the [code](https://github.com/fishtown-analytics/dbt/blob/dev/0.16.1/core/dbt/context/providers.py#L327-L334) for this.) Simply put, ephemeral models do not _have_ values of the `schema` or `database` config, since they are not materialized as a relational object in the database.

I'm going to close this issue, as I don't think we're going to make a code change around this behavior. That said, I'd be open to:
* Hearing more about your use case
* Recommending [a change to the docs site](https://github.com/fishtown-analytics/docs.getdbt.com/issues/new) to clarify that ephemeral model relations have different `schema` and `database` properties from non-ephemeral relations

**Closed by jtcohen6** 2020-07-17 14:46 UTC
Labels: bug, wontfix

**Comment by ciejer** [comment] 2020-07-17 17:59
Thanks @jtcohen6 .
We still have a broken use case, as our intended use was replacing ref with a relative ref (without DB) as described in the docs; ensuring snowflakes db clone keeps views intact.
The if statement below pastes the full code of the cte into the compile output during the comparison operation.

```
-- Macro to override ref and to render identifiers without a database, except if it is src_load. 
{% macro ref(model_name) %} 
{%- if builtins.ref(model_name).is_cte == true -%} 
{# there's a bug in dbt's handling of ref for ctes, it pastes the full WITH statement. Don't deploy this code til it's resolved #} 
{% do return(builtins.ref(model_name)) %} 

{%- elif builtins.ref(model_name).database == 'SRC_LOAD' -%} 
{% do return(builtins.ref(model_name)) %} {%- else -%} 
{% do return(builtins.ref(model_name).include(database=false)) %} 
{%- endif -%} 
{% endmacro %}
```

The above outputs the full CTE script, 'True', and the full CTE script again. Really we're just after a way of treating views differently if their DB is a certain name - can you suggest another approach?

**Comment by jtcohen6** [comment] 2020-07-19 17:12
That code seems like it works to me. Referenced ephemeral models should only interpolate their compiled SQL as a CTE once, even if they are `ref`fed several times. I added your macro to a local project and confirmed.

I may not understand your full use case. You mention a "comparison operation," could you say more about that?

As long as what you're doing is selecting from models, this seems like the desired behavior. If you're `ref`ing an ephemeral model, you _want_ its full compiled SQL interpolated as a CTE, in order to be able to select from it. If a model is non-ephemeral (view or table), your `elif`/`else` conditions manage the namespace override to exclude the `database` accordingly.
