### ISSUE TITLE
Make require_partition_filter a config option for BQ models

### ISSUE THREAD

**Issue by meurant-naude** [fishtown-analytics/dbt#2632] opened 2020-07-17 04:37 UTC
### Describe the feature
It would be good if the require_partition_filter option is available for BigQuery models. The require_partition_filter option fits with the existing partitioning option.

Our query costs are billed to the user and to prevent costly queries we have the require_partition_filter option set on our larger tables. Would be good if we can do the same with dbt generated tables.

### Describe alternatives you've considered
N/A

### Additional context
N/A

### Who will this benefit?
Any BigQuery user would benefit.

**Comment by jtcohen6** [comment] 2020-07-17 14:09
Hey @meurant-naude, this is a great idea! I'm going to close it only because it's a duplicate of #1843. We've tagged that one a "good first issue," meaning that we'd welcome a PR from a community member who wants dbt to support `require_partition_filter` as a native model config on BigQuery.

**Closed by jtcohen6** 2020-07-17 14:09 UTC
Labels: duplicate, enhancement

**Comment by meurant-naude** [comment] 2020-07-19 05:25
Hi there @jtcohen6,
Thanks for letting me know. I'll keep an eye on the other one. 
I'd love to help make the change but my python skills are still not quite there yet.
Cheers, M
