### ISSUE TITLE
except option for snapshot check all

### ISSUE THREAD

**Issue by datwiz** [fishtown-analytics/dbt#1966] opened 2019-12-02 08:24 UTC
### Describe the feature
When using the snapshot check strategy with the 'all' option add the ability to exclude specified columns, similar to the the dbt_utils.star() macro.  Add an optional 'except=[]' option to the option set when choosing check_cols='all'.

### Describe alternatives you've considered
* Option 1:  Implement a macro locally that removes excepted columns from the references relations column list.  The sequence of snapshot processing seems to be different from running a model.  Following the approach of the used in the dbt_utils.star() macro, the column list doesn't appear to be available at the time the check clauses are generated and results in an error due to empty column lists.  This may still be a viable option if there is a way to access the column list of the source relation.
* Option 2:  Explicitly list each column in each table, excluding internal processing columns.  This approach carries a risk of defects being introduced due to the large number of fields needing to be entered manually.
* Option 3:  Add an additional optional config setting.  In the .../snapshot/strategies.sql code, add a step to exclude columns from the check list based on the optional setting.  Following the approach of the star() macro, name the new field "except".

### Additional context
Working example available for a PR if this is a useful addition. 

### Who will this benefit?
Useful in cases where all business fields in a table should be checked during the snapshot process, except for operational metadata fields, like job execution date.  In our case, we have regular full refresh extracts from a source system with a significant number of generic configuration fields (50 to 100 fields depending on the extract).  We also inject lineage and operations fields into records as part of load, such as load job id and batch id.  
I want to snapshot changes based on source system changes, but not daily processing fields.  If the check snapshot strategy is used with the 'all' option, then each daily refresh is identified as an update due to the job processing fields.

**Comment by drewbanin** [comment] 2019-12-20 19:47
hey @datwiz - thanks for opening this issue!

I totally buy what you're describing and agree that an `except` option would help address this use case. That said, setting `check_cols` to `all` is provided for convenience and is not considered a best practice (see here: https://docs.getdbt.com/docs/snapshots#section-check) so I hesitate to add more complications to that particular piece of functionality.

I'm closing this issue out with a wontfix label to indicate that it's not something we'll be able to add support for in dbt. That said, I do totally think this is something you could implement in your own project, no changes to dbt required. You said:

> Option 3: Add an additional optional config setting. In the .../snapshot/strategies.sql code, add a step to exclude columns from the check list based on the optional setting. Following the approach of the star() macro, name the new field "except".

You can in fact copy the check strategy macro into your own macro, rename it, and then use your custom strategy in your snapshot definitions. Check out the source code here:
https://github.com/fishtown-analytics/dbt/blob/8cd8705d67627e8f701afb5f5490d553e76f3dfa/core/dbt/include/global_project/macros/materializations/snapshot/strategies.sql#L122-L169

So, you could rename this macro to `snapshot_check_except_strategy`, then update the macro to accept a config called `except`. In your snapshot file, you would use the strategy named `check_except`:

```
{% snapshot my_snapshot %}

    {{
        config(
          target_schema='snapshots',
          strategy='check_except',
          except=['abc', 'def'],
          unique_key='id',
          check_cols=['status', 'is_cancelled'],
        )
    }}

select ...
```

I'm closing this one out, but happy to follow up below if you have any questions or thoughts :)

**Closed by drewbanin** 2019-12-20 19:47 UTC
Labels: wontfix

**Comment by datwiz** [comment] 2019-12-22 11:11
Thanks @drewbanin for the detailed feedback.

Rounding out the close out, after a bit more investigation into source data, I've identified a suitable field to use as an 'updated_at' value and switched to the snapshot timestamp method.  This avoids the need for checking all those sparsely populated generic columns provided by the upstream source..

**Comment by walker-philips** [comment] 2024-01-31 15:42
I have a similar scenario where the except functionality would be ideal. I am dealing with an external data source of over 200 columns. It fails to provide an updated at column (the database was seemingly built in the 90's). The data source has new columns added every so often. I need to dynamically update the check_cols to exclude some of the more trivial columns and false-positive columns (ones that change every day but mean nothing). An except feature would make this seamless.

Your point of it being dangerous is understood, but given how DBT seems to embrace being dynamic-friendly SQL, this allows snapshots to adapt to changing data sources, encouraging more data to be captured even if a new column artificially increases the capture rate. I see this as no riskier than explicitly typed columns in check_cols, given both approaches require a manual intervention to correct. 

I tried a workaround attempting to use dbt_utils.get_filtered_columns_in_relation but it fails the pre-execute phase (which seems by design). Attempts to fake it out also dont lead to desired results. Maybe I am missing something?

**Comment by stefanengelmann** [comment] 2025-03-28 10:02
In case it is useful for anyone, I customized the source code for the `check` strategy to obtain a  `check_except` strategy:

```
{% macro snapshot_check_except_strategy(node, snapshotted_rel, current_rel, config, target_exists) %}
    {% set except_cols = config.get('except', []) %}
    {% set primary_key = config['unique_key'] %}
    {% set invalidate_hard_deletes = config.get('invalidate_hard_deletes', false) %}
    {% set updated_at = config.get('updated_at', snapshot_get_time()) %}

    {% set _ , all_cols = snapshot_check_all_get_existing_columns(node, target_exists, "all") %}
    {% set check_cols = [] %}
    {% for col in all_cols %}
        {% set normalized_col = col | replace('"', '') | lower %}
        {% set normalized_except_cols = except_cols | map('lower') | list %}
        {% if normalized_col not in normalized_except_cols %}
            {% do check_cols.append(col) %}
        {% endif %}
    {% endfor %}

    {%- set row_changed_expr -%}
    (
    {%- for col in check_cols -%}
        {{ snapshotted_rel }}.{{ col }} != {{ current_rel }}.{{ col }}
        or
        (
            (({{ snapshotted_rel }}.{{ col }} is null) and not ({{ current_rel }}.{{ col }} is null))
            or
            ((not {{ snapshotted_rel }}.{{ col }} is null) and ({{ current_rel }}.{{ col }} is null))
        )
        {%- if not loop.last %} or {% endif -%}
    {%- endfor -%}
    )
    {%- endset %}

    {% set scd_id_expr = snapshot_hash_arguments([primary_key, updated_at]) %}

    {% do return({
        "unique_key": primary_key,
        "updated_at": updated_at,
        "row_changed": row_changed_expr,
        "scd_id": scd_id_expr,
        "invalidate_hard_deletes": invalidate_hard_deletes
    }) %}
{% endmacro %}
```
