### ISSUE TITLE
Composite key as `unique_key` - list of columns

### ISSUE THREAD

**Issue by JCZuurmond** [fishtown-analytics/dbt#3431] opened 2021-06-04 14:19 UTC
### Describe the feature

Use a composite key as [`unique_key`](https://docs.getdbt.com/reference/resource-configs/unique_key). Optionally the user can specify a list of strings, instead of just a string. Then the adapters could use that list to create the condition on multiple columns - a composite key.

``` python
unique_key = ["column_a", "column_b"]
```

### Describe alternatives you've considered

The alternative described on the `unique_key` [page](https://docs.getdbt.com/reference/resource-configs/unique_key#use-a-combination-of-two-columns-as-a-unique-key). I do not like that I have to create an additional column based on string concatenation, preferably this is not necessary.

### Additional context

It affects the databases which support [incremental](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/configuring-incremental-models#what-is-an-incremental_strategy) strategy.

### Who will this benefit?

Me. And other people who use composite keys and do not prefer to create an additional column based on string concatenation.

### Are you interested in contributing this feature?

Yes, I expect that the code in `dbt` is minimal. I would allow to optionally make the `unique_key` a list of string (instead of just string). Then the logic should be implemented at the specific database extension to utilize it for a composite key. As far as I can tell, it could be implemented as a non-breaking change by allowing `unique_key` to be both a `str` or `List[str]`.

**Comment by jtcohen6** [comment] 2021-06-07 17:00
@JCZuurmond I'm all about it!

This issue is _sort of_ a duplicate of https://github.com/fishtown-analytics/dbt/issues/2479, though that one was specific to incremental models, and you've also got snapshots in mind. We got most of the way there, but it never made it into a contribution. If you'd be interested in picking this up, I'd love that!

One thing I'll call out:
> by allowing `unique_key` to be both a `str` or `List[str]`.

The `unique_key` config is funny because it's actually _not_ specified in [`model_config.py`](https://github.com/fishtown-analytics/dbt/blob/develop/core/dbt/contracts/graph/model_config.py) for models, only for snapshots. It still works for incremental models: it's just referenced in Jinja materializations via `config.get('unique_key')`, and we document that it's a string named `unique_key`, but there's no python-level validation.

I'd much prefer to have `unique_key` defined in python for both resource types. If we do that, I think we may finally want to split out a `ModelConfig` class from the generic `NodeConfig` class, as the rightful home for model-specific configs like `full_refresh`, `unique_key`, and `incremental_strategy` (which is also undefined in python but regularly called by Jinja in the incremental materialization).

That doesn't have to be in the scope of resolving this particular issue, but it's something on my mind.

**Comment by JCZuurmond** [comment] 2021-06-12 09:19
Hi @jtcohen6, thanks for your reply!

I don't expect to have time for this soon. So if someone else wants to implement this then that person should go ahead. 

The mentioned issue covers what I expect to implement. I'll close this one so that we have our discussions in one place.

**Closed** 2021-06-12 09:20 UTC
Labels: enhancement, snapshots
