### ISSUE TITLE
changing materialization from table to view throws rename error

### ISSUE THREAD

**Issue by danielefrigo** [fishtown-analytics/dbt#3481] opened 2021-06-21 17:28 UTC
### Describe the bug
When you change the materialization of a model from table to view (or the opposite), you get an object type error because dbt is building the rename statement (from target to backup) based on the model type instead of the db object type.

### Steps To Reproduce
Create a model with table materialization, run it once, than change the materialization to view.

### Expected behavior
dbt should backup the table and create the new view.

### System information
Netezza

**The output of `dbt --version`:**
```
installed version: 0.19.1
   latest version: 0.19.1

Up to date!

Plugins:
```

**The operating system you're using:**
Windows

**The output of `python --version`:**
Python 3.8.5

### Additional context
Per my understanding, the issue can be fixed changing https://github.com/fishtown-analytics/dbt/blob/c712c96a0b0c03389cb8769ea4a1c437076d1d06/core/dbt/include/global_project/macros/materializations/view/view.sql#L50 into     {{ adapter.rename_relation(old_relation, backup_relation) }} (and similarly in table materialization)

**Comment by jtcohen6** [comment] 2021-06-21 18:00
Thanks @danielefrigo!

I encountered the same issue with the dbt-presto adapter plugin a while back (https://github.com/fishtown-analytics/dbt-presto/pull/13), and opened https://github.com/fishtown-analytics/dbt/issues/2161 to track the fix for the default materializations. It looks like we still haven't circled back to make that fix. Would you be interested in contributing it? :)

(In the meantime, I'm going to close this issue as a duplicate of #2161)

**Closed by jtcohen6** 2021-06-21 18:00 UTC
Labels: bug, duplicate

**Comment by danielefrigo** [comment] 2021-07-06 14:20
@jtcohen6 it took me a lot to find the time, but I finally managed to set up the environment for the testing as explained [here](https://github.com/dbt-labs/dbt/blob/c794600242e734d870d4bf1c8fb4c0349ab961eb/CONTRIBUTING.md#setting-up-an-environment).
I will try opening my first pull request for this issue.
