### ISSUE TITLE
Snowflake Information Schema Query Error

### ISSUE THREAD

**Issue by TaliaSRTR** [fishtown-analytics/dbt#1127] opened 2018-11-14 22:55 UTC
## Issue
DBT is sporadically throwing the following Snowflake error upon build of an incremental model: `Information schema query returned too much data.  Please repeat query with more selective predicates.`

### Issue description
I run my DBT project simply using `dbt  run`. In my project, I have a couple of incremental models, and occasionally the project fails to build when trying to build one of these models.

### Results
The compiled query in Snowflake that's failing looks like the following:

```
select
    column_name,
    data_type,
    character_maximum_length,
    numeric_precision || ',' || numeric_scale as numeric_size
from information_schema.columns
where table_name ilike '<MODEL_ALIAS>__dbt_incremental_tmp'
  and 1=1
order by ordinal_position
```
This is the query that throws error mentioned above.

### System information
The output of `dbt --version`:
```
0.11.1
```

The operating system you're running on:

The python version you're using (probably the output of `python --version`)
```
Python 2.6.6
```

### Steps to reproduce
I simply run `dbt run` in my project, and I see this in my log output:
```
2 of 16 START incremental model <MODEL_NAME>........... [RUN]
2 of 16 ERROR creating incremental model <MODEL_NAME>.. [ERROR in 133.84s]
```

My model is configured as such:
```{{
  config({
      "schema" : "<SCHEMA>"
    , "alias" : "<ALIAS>"
    , "materialized" : "incremental"
    , "sql_where" : "TRUE"
    , "unique_key" : "<KEY_ID>"
    , "post-hook" : [
        "ALTER TABLE {{ this }} CLUSTER BY (<CLUSTER_KEY>)"
      , "ALTER TABLE {{ this }} RECLUSTER"
    ]
  })
}}
```
In my model, I use this Jinja template (taken straight from the DBT docs): `{% if adapter.already_exists(this.schema, this.table) and not flags.FULL_REFRESH %}` to add a condition that determines which new records are to be pulled into the table.

**Comment by TaliaSRTR** [comment] 2018-11-14 22:56
I contacted Snowflake's support about this issue, and was given this response:

```
INFORMATION_SCHEMA queries are pushed down to our metadata system, which can't use the filters you specified, and consequently returns much more data than expected.

The good news is that we now have a much better way to retrieve the same information without these limitations. You should have a schema SNOWFLAKE.ACCOUNT_USAGE in your account, which has a view called COLUMNS, corresponding to the INFORMATION_SCHEMA.COLUMNS view. 

By default, only account administrators (users with the ACCOUNTADMIN role) can access the SNOWFLAKE database and schemas and perform queries on the views; however, privileges for these objects can be granted to other roles in your account to allow users with the roles to access the objects.
```
I'm not sure if it's more appropriate to escalate this issue with dbt or with Snowflake, but this seems it might be a useful piece of information?

**Comment by drewbanin** [comment] 2018-11-14 23:44
hey @TaliaSRTR - thanks for the report and sorry for the trouble.

I think that `ACCOUNT_USAGE` probably won't be tenable for us here, as the data in that schema can be delayed by up to three hours!

From the [docs](https://docs.snowflake.net/manuals/sql-reference/account-usage.html#data-latency):
> Due to the process of extracting the data from Snowflake’s internal metadata store, the account usage views have some natural latency:
>    For most of the views, the latency is 2 hours (120 minutes).
>    For the other views, the latency varies between 45 minutes and 3 hours.

For context, dbt is running the query against `information_schema.columns` in order to generate the `insert` statement used in incremental models. In very short, dbt runs something like:

```sql
create temp table <MODEL_ALIAS>__dbt_incremental_tmp as (
  select ... -- your model SQL here
)

-- dbt fetches the columns in <MODEL_ALIAS>__dbt_incremental_tmp here

insert into <MODEL_ALIAS> (col1, col2, col3, ...) (
  select col1, col2, col3, ...
  from <MODEL_ALIAS>__dbt_incremental_tmp
)
```

dbt needs to know the columns in the table in order to do all of this correctly. Since the query for the columns happens directly after the temp table is created, I'm not sure that a 2 hour delay would work for us here!

So, I think there are some options here:
1. dbt could use a different type of query on Snowflake? We use `ilike` to work around Snowflake quoting weirdness (default=uppercase), but maybe something like
```
where table_name = upper('<MODEL_ALIAS>__dbt_incremental_tmp')
   or table_name = lower('<MODEL_ALIAS>__dbt_incremental_tmp')
```

^ this won't be perfect, and I'm not certain that Snowflake's metadata layer will fare any better, but it could be worth exploring.

2. You could try building your dbt models in a different logical database. The `information_schema.columns` table is different for each logical database, and I imagine that you won't hit this error if you have fewer objects in the database that dbt is querying.

3. dbt could do something totally different. We could find the columns in the temp table by running a query like:
```
select * from <MODEL_ALIAS>__dbt_incremental_tmp limit 0
```

^ I'd prefer not to do this I think, but it is another option that wouldn't suffer from this limitation.

Keen to hear your thoughts, and definitely feel free to relay this feedback to Snowflake if you think it will be helpful!

**Comment by NoazDad** [comment] 2019-01-11 15:35
```
select
    column_name,
    data_type,
    character_maximum_length,
    numeric_precision || ',' || numeric_scale as numeric_size
from information_schema.columns
where table_name ilike '<MODEL_ALIAS>__dbt_incremental_tmp'
  and 1=1
order by ordinal_position ;
```

This could just be a malformed query...  Shouldn't there be a '%' somewhere in that iLike argument? 
```
where table_name iLike '<MODEL_ALIAS>__dbt_incremental_tmp%'
```
In a typical DBT installation, how many tables will exist in the schema that match this pattern?  

-Paul-
(I'm a Solution Architect with Snowflake...)

**Comment by NoazDad** [comment] 2019-01-11 15:43
FYI: here's the bible on how Snowflake resolves identifier names.
1) If you created the object without quoted identifier, then all queries resolve to UPPER_CASE, and any specified pattern will match:  
```
create table mY_TaBle ( ... );  
select * from MY_TABLE;  -- works fine
select * from My_taBLe;   -- works fine
```
2) If you created the object WITH quoted identifiers, then it will only resolve if the identifier matches exactly.  
```
create table "my_Table" () ;
select * from my_Table;  -- works fine
select * from MY_TABLE;  -- object not found
```
HTH,
-Paul-

**Comment by drewbanin** [comment] 2019-01-11 19:57
Hi @NoazDad! Super glad you found this issue :) 

dbt runs some queries against the `information_schema` to find:
1) the schemas that exist in a database
2) the relations that exist in a schema
3) the columns that exist in a relation

The query shown in the body of this issue is in the third category -- dbt is trying to find the columns in a relation called something like `orders_dbt_incremental_tmp`. Due to the intricacies you've noted around Snowflake's approach to quoting (plus the incidence of configs like ` QUOTED_IDENTIFIERS_IGNORE_CASE`), we've decided to just make all `information_schema` queries case-insensitive. In the following query, the `ilike` without the `%` is used to do a case-insensitive match for a relation called `orders_dbt_incremental_tmp`.

```
select
    column_name,
    data_type,
    character_maximum_length,
    numeric_precision || ',' || numeric_scale as numeric_size
from information_schema.columns
where table_name ilike 'orders_dbt_incremental_tmp'
  and 1=1
order by ordinal_position
```

^ Looking at this again, I notice that dbt isn't filtering on `table_schema` here. It was my impression that dbt should be applying a filter for the `table_schema`, and I think that omission is probably contributing to the behavior described in this issue. I'm going to try to reproduce this in dbt v0.11.1 to make sure that that's actually what's happening. Will follow up here for sure.

> In a typical DBT installation, how many tables will exist in the schema that match this pattern?

I imagine for most deployments, there are between 25-150 relations present in one of these schemas. It's possible for there to be more though -- I'm sure someone out there has closer to ~300. If everything is working correctly, there should only be a single table in a given schema that matches this pattern, case-insensitively.

Would love to hear your thoughts on this -- thanks!

**Comment by sairamroofstock** [comment] 2019-04-25 13:47
Hi @drewbanin , 

Any update on this? 

It looks like there is nothing wrong from snowflake side as well, rather they are just asking to put some predicate filter to prevent such performance issues. 

Refer the issue below in snowflake: 
https://community.snowflake.com/s/article/error-information-schema-query-returned-too-much-data-please-repeat-query-with-more-selective-predicates-when-querying-information-schema-view

Can we some how fix this issue by discussing with snowflake, let me know if there's any option as such. 

Thanks!

**Comment by drewbanin** [comment] 2019-04-25 15:04
Hey @sairamroofstock - unfortunately no update here on our end.

It's not clear to me how dbt should be querying the information schema tables. If there was a well defined row limit or response size imposed by Snowflake, then we would at least know what our constraints are. As it stands, Snowflake just errors out if "too much" data is returned from an information schema query.

This is complicated by the fact that information schema queries are _really slow_ on Snowflake. At present, dbt fetches information about a whole `schema` at once from `information_schema.tables`. This is faster than querying for each table individually, but comes with the caveat that sometimes these queries fail.

If you're able to get in touch with Snowflake support, they might be able to give you more information (which I hope you can share with us here!). My recommendation would be to run your dbt project in its own database, as this seems to reduce the incidence of this type of error.

**Comment by drewbanin** [comment] 2019-12-04 17:40
This is still a big problem, but for organizational reasons, I'm closing this issue in favor of https://github.com/fishtown-analytics/dbt/issues/1877

We're prioritizing a fix for this issue (and other information schema issues on Snowflake) presently.

**Closed by drewbanin** 2019-12-04 17:40 UTC
Labels: snowflake
