### ISSUE TITLE
Indefinite Snowflake auth loop  when using browser authentication

### ISSUE THREAD

**Issue by eugene-nikolaev** [fishtown-analytics/dbt#2689] opened 2020-08-06 08:36 UTC
### Describe the bug
We encounter indefinite auth loop while running dbt with browser auth enabled

### Steps To Reproduce
Install dbt 0.17.2 and run anything on Snowflake

### Expected behavior
Expected two auth requests in case of MFA and dbt proceeding to transform.
(non-MFA logins fail into the loop too)

### Screenshots and log output
```
(dbt-transformations) <wiped out>@<wiped out> dbt-transformations % dbt run --models <wiped out>
Running with dbt=0.17.2
Found 129 models, 135 tests, 3 snapshots, 0 analyses, 140 macros, 0 operations, 1 seed file, 53 sources

Initiating login request with your identity provider. A browser window should have opened for you to complete the login. If you can't see it, check existing browser windows, or your OS settings. Press CTRL+C to abort and try again...
Initiating login request with your identity provider. A browser window should have opened for you to complete the login. If you can't see it, check existing browser windows, or your OS settings. Press CTRL+C to abort and try again...
Initiating login request with your identity provider. A browser window should have opened for you to complete the login. If you can't see it, check existing browser windows, or your OS settings. Press CTRL+C to abort and try again...
Initiating login request with your identity provider. A browser window should have opened for you to complete the login. If you can't see it, check existing browser windows, or your OS settings. Press CTRL+C to abort and try again...
Initiating login request with your identity provider. A browser window should have opened for you to complete the login. If you can't see it, check existing browser windows, or your OS settings. Press CTRL+C to abort and try again...
^C^C^Cctrl-c

```

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.17.2
   latest version: 0.17.2

Up to date!

Plugins:
  - bigquery: 0.17.2
  - snowflake: 0.17.2
  - redshift: 0.17.2
  - postgres: 0.17.2
```

**The operating system you're using:**
MacOS 10.15.5 (19F101)

**The output of `python --version`:**
Python 3.7.7

### Additional context
reverting dbt to 0.17.1 fixed the issue

**Comment by jtcohen6** [comment] 2020-08-06 14:45
Hey @eugene-nikolaev, thanks for opening this issue.

Which MFA mechanism are you using for your Snowflake account? dbt connects to Snowflake via its python connector, which [uses Duo Push by default](https://docs.snowflake.com/en/user-guide/security-mfa.html#using-mfa-with-python). That's how I've done dbt CLI + Snowflake + MFA in the past.

It's helpful to know that reverting to v0.17.1 fixes the issue. We made two relevant changes in v0.17.2:
* #2635: added an env var (`DBT_SNOWFLAKE_CONNECTOR_DEBUG_LOGGING`) to turn on debug-level logging from Snowflake's python connector
* #2650: close open Snowflake connections after using them

I'm guessing that the latter be at issue, and the former may help us troubleshoot what's going on.

**Comment by eugene-nikolaev** [comment] 2020-08-06 15:00
@jtcohen6 thanks for reply.
Yes it is Duo Mobile for MFA.
However it isn't related to MFA in any way because other developer has the same without MFA.

**Comment by beckjake** [comment] 2020-08-06 15:00
It's definitely going to be the latter. Fixing this is going to be a bit involved, unfortunately.

Instead of closing everything we'll have to go back to the old way of not calling `close` when the connection is open. Then we'll have to do something clever to make sure `close` gets called so we don't deadlock with the keepalive thread again. I'm not sure what that means happens to MFA if a model hits a connection-closing error on 0.17.1. Do we make you re-auth?

**Comment by jtcohen6** [comment] 2020-08-06 15:53
@eugene-nikolaev Got it, I think your best bet for now is to use v0.17.1

@beckjake Let's pull this into v0.18.0, if possible

**Comment by eugene-nikolaev** [comment] 2020-08-07 15:03
@jtcohen6, @beckjake, got it, thanks! Will wait.

**Comment by beckjake** [comment] 2020-08-12 16:42
I think instead of reverting that change (which is still on the table, though I would rather avoid it) we may be able to fix this by implementing #2613. It appears to me that on Linux, the token cache is global to the executing user (in `~/.cache/snowflake/` by default). I think that would solve these issues pretty nicely, though of course you'd have to enable the token cache on the server. I'm not super clear on the mac/windows flow, it looks like it uses the os' "keyring" mechanism, whatever that is.

Is that a reasonable approach?

https://github.com/snowflakedb/snowflake-connector-python/blob/0215c0adadbbff6b33dfa32e52a1d0d887f557cf/auth.py#L50

**Closed** 2020-08-14 19:47 UTC
Labels: bug

**Comment by tonyqiu2020** [comment] 2020-09-11 13:35
@beckjake We still have the same issue after upgrading to 0.18. The latest working version is 0.17.1

**Comment by beckjake** [comment] 2020-09-11 15:02
@tonyqiu2020 are you on windows/mac? Does `pip install keyring` fix it, by any chance?

**Comment by thillerdal** [comment] 2020-09-16 13:55
@beckjake we have this issue as well (appeared when upgrading from 0.17.2 to 0.18.0). We're running okta, snowflake and a variety of pc and mac configs. 

We first changed `alter account set allow_id_token = true`, but that did not help. `pip install keyring`, however, seems to fix the issue!

**Comment by tonyqiu2020** [comment] 2020-09-16 18:31
`pip install keyring` fixed the issue.

**Comment by Plamen8780** [comment] 2020-09-17 19:52
I followed the steps above but I still have this issue.

I'm using dbt 0.18.0 on Mac.
Installed keyring with `pip install keyring`
Executed `alter account set allow_id_token = true` on Snowflake

When I execute `dbt run` it just starts an infinite loop of authentications in Duo Mobile and I have to kill it.
Do I have to configure something in keyring?

**Comment by jtcohen6** [comment] 2020-09-21 19:48
Hey @Plamen8780, I'm thinking that may be a different issue? The issue here is an infinite loop of `externalbrowser` authentication, whether the user has MFA turned on or not.

How many threads are you running dbt with against Snowflake? Last time I did this, I recall needing to authenticate in Duo Mobile once for each thread at the start of a run.

**Comment by Plamen8780** [comment] 2020-09-21 19:59
@jtcohen6 , you are right it is slightly different - I'm using password authentication and I have MFA turned on but it still results in an infinite Duo authentication loop.
I'm using just one thread. I also tried clicking "Yes" in Duo at least 20 times before giving up.

**Comment by jtcohen6** [comment] 2020-09-21 20:11
@Plamen8780 Got it. Could you try watching the dbt logs (e.g. `tail -f logs/dbt.log`) when you `dbt run`? I'd be curious to know if you're getting one Duo Push per metadata query that dbt is running, or if it is indeed an infinite loop not tied to any specific set of queries.

**Comment by Plamen8780** [comment] 2020-09-21 20:48
@jtcohen6 , this is how the log looks like before I installed keyring:
```
2020-09-17 14:12:47.346320 (MainThread): Acquiring new snowflake connection "model.tide.latest_codes".
2020-09-17 14:12:47.346482 (MainThread): Opening a new connection, currently in state init
2020-09-17 14:12:47.379310 (MainThread): Acquiring new snowflake connection "model.tide.latest_code_usages".
2020-09-17 14:12:47.379451 (MainThread): Opening a new connection, currently in state init
2020-09-17 14:12:47.393309 (MainThread): Acquiring new snowflake connection "model.tide.latest_company_formations_users".
2020-09-17 14:12:47.393444 (MainThread): Opening a new connection, currently in state init
2020-09-17 14:12:47.406594 (MainThread): Acquiring new snowflake connection "model.tide.latest_company_formations_businesses".
2020-09-17 14:12:47.406734 (MainThread): Opening a new connection, currently in state init
2020-09-17 14:12:47.420416 (MainThread): Acquiring new snowflake connection "model.tide.latest_company_formations_applications".
2020-09-17 14:12:47.420574 (MainThread): Opening a new connection, currently in state init
2020-09-17 14:12:47.435721 (MainThread): Acquiring new snowflake connection "model.tide.latest_virtual_address_usage".
2020-09-17 14:12:47.435854 (MainThread): Opening a new connection, currently in state init
...
```

And this is after keyring:
```
2020-09-17 17:46:50.545057 (MainThread): Acquiring new snowflake connection "model.tide.latest_codes".
2020-09-17 17:46:50.571224 (MainThread): Acquiring new snowflake connection "model.tide.latest_code_usages".
2020-09-17 17:46:50.585056 (MainThread): Acquiring new snowflake connection "model.tide.latest_company_formations_users".
2020-09-17 17:46:50.598730 (MainThread): Acquiring new snowflake connection "model.tide.latest_company_formations_businesses".
2020-09-17 17:46:50.612737 (MainThread): Acquiring new snowflake connection "model.tide.latest_company_formations_applications".
2020-09-17 17:46:50.627212 (MainThread): Acquiring new snowflake connection "model.tide.latest_virtual_address_usage".
...
```

So it seems like it tries to acquire connection for each model. But not sure why keyring doesn't work here.

**Comment by jtcohen6** [comment] 2020-09-22 19:05
@Plamen8780 When are you seeing the Duo pushes? Is it before/after every single one of those `Acquiring new snowflake connection`? Or a completely unrelated phenomenon?

**Comment by feluelle** [comment] 2021-10-01 07:38
The issues is not fixed @jtcohen6. We are still facing it and probably will use a different auth method then. :/

cc @pecigonzalo

**Comment by jtcohen6** [comment] 2021-10-01 13:11
@feluelle Are you using the latest versions of `dbt-snowflake` and `snowflake-connector-python`, with `keyring` installed?

**Comment by feluelle** [comment] 2021-10-01 15:11
Yes, I am using the latest version of all three. But it might be still related to the connector and has nothing to do with dbt. See https://github.com/snowflakedb/snowflake-connector-python/issues/349 WDYT Jeremy? :)

**Comment by JudyCamps** [comment] 2022-07-11 14:51
I am experiencing this issue in dbt 1.1.0 with Snowflake and OKTA on a macbook.  
The terminal window says 
`Initiating login request with your identity provider. A browser window should have opened for you to complete the login. If you can't see it, check existing browser windows, or your OS settings. Press CTRL+C to abort and try again...
`
It keeps opening browser windows that say "Your identity was confirmed and propagated to Snowflake dbt. You can close this window now and go back where you started from."

So it seems OKTA is returning the token but dbt core is not accepting it.  I have keyring installed.

**Comment by joaopmoniz** [comment] 2022-07-12 07:18
I have the same as @JudyCamps, very similar environment.
I am using Mac, `dbt core 1.1.1` and `snowflake plugin 1.1.0`. I already have the `keyring` installed, and we've set the `alter account set allow_id_token = true` with the `externalbrowser` config on the profile. Same problem as above.

**Comment by JimMcKenzieSmith** [comment] 2022-08-10 20:54
I'm having the same issue as @JudyCamps and @joaopmoniz.

- This was working on a previous Mac. I upgraded to a new Mac and this started happening. 
- dbt core `1.2.0` (latest)
- snowflake plugin `1.2.0` (latest)
- `keyring` is installed
- `alter account set allow_id_token = true` is set on Snowflake (same as before) with the `externalbrowser` config on the profile (as I said, it still works great on my old Macbook)

I've inspected `dbt.log`.  It seems to be opening a new connection over and over again for each test that is trying to run, instead of reusing the same connection.  Here is some log output for one of the threads (this cycles over and over for each test).  In my case, I have 10 threads, and each of the threads is unable to reuse their connection. So, I end up with hundreds of browser tabs that open instead of just 10.  I masked our column and table names with `****` for confidentiality:
```
20:18:03.317310 [debug] [Thread-5  ]: Began running node test.****.dbt_expectations_expect_column_values_to_be_of_type_****__number.80365b549a
20:18:03.321283 [info ] [Thread-5  ]: 88 of 122 START test dbt_expectations_expect_column_values_to_be_of_type_****__number  [RUN]
20:18:03.331279 [debug] [Thread-5  ]: Acquiring new snowflake connection "test.****.dbt_expectations_expect_column_values_to_be_of_type_****__number.80365b549a"
20:18:03.334920 [debug] [Thread-5  ]: Began compiling node test.****.dbt_expectations_expect_column_values_to_be_of_type_****__number.80365b549a
20:18:03.336249 [debug] [Thread-5  ]: Compiling test.****.dbt_expectations_expect_column_values_to_be_of_type_****__number.80365b549a
20:18:03.346220 [debug] [Thread-5  ]: Using snowflake connection "test.****.dbt_expectations_expect_column_values_to_be_of_type_****__number.80365b549a"
20:18:03.346786 [debug] [Thread-5  ]: On test.****.dbt_expectations_expect_column_values_to_be_of_type_****__number.80365b549a: /* {"app": "dbt", "dbt_version": "1.2.0", "profile_name": "snowflake_data_transformation", "target_name": "dev", "node_id": "test.****.dbt_expectations_expect_column_values_to_be_of_type_****__number.80365b549a"} */
20:18:03.347187 [debug] [Thread-5  ]: Opening a new connection, currently in state closed
20:18:05.846210 [debug] [Thread-5  ]: SQL status: SUCCESS 46 in 2.5 seconds
20:18:05.879990 [debug] [Thread-5  ]: Writing injected SQL for node "test.****.dbt_expectations_expect_column_values_to_be_of_type_****__number.80365b549a"
20:18:05.887660 [debug] [Thread-5  ]: finished collecting timing info
20:18:05.887881 [debug] [Thread-5  ]: Began executing node test.****.dbt_expectations_expect_column_values_to_be_of_type_****__number.80365b549a
20:18:05.889726 [debug] [Thread-5  ]: Writing runtime SQL for node "test.****.dbt_expectations_expect_column_values_to_be_of_type_****__number.80365b549a"
20:18:05.897788 [debug] [Thread-5  ]: Using snowflake connection "test.****.dbt_expectations_expect_column_values_to_be_of_type_****__number.80365b549a"
20:18:05.898073 [debug] [Thread-5  ]: On test.****.dbt_expectations_expect_column_values_to_be_of_type_****__number.80365b549a: /* {"app": "dbt", "dbt_version": "1.2.0", "profile_name": "snowflake_data_transformation", "target_name": "dev", "node_id": "test.****.dbt_expectations_expect_column_values_to_be_of_type_****__number.80365b549a"} */
20:18:06.482789 [debug] [Thread-5  ]: SQL status: SUCCESS 1 in 0.58 seconds
20:18:06.483651 [debug] [Thread-5  ]: finished collecting timing info
20:18:06.483756 [debug] [Thread-5  ]: On test.****.dbt_expectations_expect_column_values_to_be_of_type_****__number.80365b549a: Close
20:18:06.698643 [info ] [Thread-5  ]: 88 of 122 PASS dbt_expectations_expect_column_values_to_be_of_type_****__number  [PASS in 3.37s]
20:18:06.701148 [debug] [Thread-5  ]: Finished running node test.****.dbt_expectations_expect_column_values_to_be_of_type_****__number.80365b549a
```
Then Thread-5 goes into another cycle and gets a new connection instead of reusing:
```
20:18:06.701962 [debug] [Thread-5  ]: Began running node test.****.field_is_unique_****.ae3cd8dc26
20:18:06.702969 [info ] [Thread-5  ]: 98 of 122 START test field_is_unique_**** ................. [RUN]
20:18:06.703746 [debug] [Thread-5  ]: Acquiring new snowflake connection "test.****.field_is_unique_****.ae3cd8dc26"
...
```
Is there something I could compare on my old Macbook to see what is going on?

**Comment by HorvathDanielMarton** [comment] 2022-10-13 12:26
I experience the same problem as well on Rosetta terminal. Installed `dbt-snowflake` via Homebrew.
```
Core:
  - installed: 1.3.0
  - latest:    1.3.0 - Up to date!

Plugins:
  - snowflake: 1.3.0 - Up to date!

python3 --version
Python 3.9.6
```

**Comment by leahwicz** [comment] 2022-10-27 17:21
We have an open issue specifically for this in the Snowflake repo here with some solutions on how people unblocked themselves

https://github.com/dbt-labs/dbt-snowflake/issues/208
