### ISSUE TITLE
Last call statement in for loop returns "False" instead of actual data

### ISSUE THREAD

**Issue by tayloramurphy** [fishtown-analytics/dbt#860] opened 2018-07-17 21:55 UTC
I was able to simplify my macro to the following and still reproduce this. dbt version 0.10.1 on Python 3.5.3

```
{% macro test_false_result(input_id) %}

    {% for i in range(0, 3) %}

        {% for j in range(0, 5) %}

              {% set splice = i * 5 + j + 1 %}


              {% call statement('j_sub', fetch_result=True) %}
                SELECT substr('{{input_id}}','{{splice}}',1)
              {% endcall %}


              {% set chr_results = load_result('j_sub') %}

                {{ log(chr_results~ " This is chr_results" ) }}

              {% set chr = chr_results['data'] %}

                {{ log(chr ~ " This is chr" ) }}

        {% endfor %}

    {% endfor %}

{% endmacro %}
```

For a model that has the calls the macro in the following way

```
SELECT
    {{ model.test_false_result('7016100000082bN') }}
```

I'm seeing that the last few log items look like this:

```
018-07-17 16:41:38,803: Using postgres connection "testsfdcid".
2018-07-17 16:41:38,803: On testsfdcid: 
                SELECT substr('7016100000082bN','13',1)
              
2018-07-17 16:41:38,874: SQL status: SELECT 1 in 0.07 seconds
2018-07-17 16:41:38,876: {'status': 'SELECT 1', 'table': <agate.table.Table object at 0x108e13f60>, 'data': [(Decimal('2'),)]} This is chr_results
2018-07-17 16:41:38,876: [(Decimal('2'),)] This is chr
2018-07-17 16:41:38,878: Using postgres connection "testsfdcid".
2018-07-17 16:41:38,878: On testsfdcid: 
                SELECT substr('7016100000082bN','14',1)
              
2018-07-17 16:41:38,954: SQL status: SELECT 1 in 0.08 seconds
2018-07-17 16:41:38,955: {'status': 'SELECT 1', 'table': <agate.table.Table object at 0x108e13748>, 'data': [('b',)]} This is chr_results
2018-07-17 16:41:38,956: [('b',)] This is chr
2018-07-17 16:41:38,957: Using postgres connection "testsfdcid".
2018-07-17 16:41:38,958: On testsfdcid: 
                SELECT substr('7016100000082bN','15',1)
              
2018-07-17 16:41:39,030: SQL status: SELECT 1 in 0.07 seconds
2018-07-17 16:41:39,031: {'status': 'SELECT 1', 'table': <agate.table.Table object at 0x108e134e0>, 'data': [(False,)]} This is chr_results
2018-07-17 16:41:39,031: [(False,)] This is chr
2018-07-17 16:41:39,038: Writing injected SQL for node "model.gitlab_dw.testsfdcid"
```

So you can see that the call statement works as expected up until the last one where the `data` key contains `[(False,}]` instead of the expected ` [('N',)]`. 

Thoughts on this?

**Comment by drewbanin** [comment] 2018-07-17 22:05
@tayloramurphy I think this is caused by Agate, the dataframe lib that dbt uses. It pretty aggressively casts values to Boolean types, which is almost never desirable for us. It also has the adverse effect of casting the country code for Namibia (NA) to `null`. More info over here: http://agate.readthedocs.io/en/1.6.0/api/data_types.html#agate.Boolean

**Comment by tayloramurphy** [comment] 2018-07-17 22:22
@drewbanin ah, that's a bummer. I'm trying to implement a SFDC 15 to 18 character converter and I have to convert each character to its ascii value, do some bitwise manipulation, then convert back.  I'll explicitly handle the Y and N cases I think.

**Comment by drewbanin** [comment] 2018-07-17 22:29
roger. We're going to fix this, as it's a pretty unfortunate bug right now. In the meantime, i'd recommend not actually hitting the database once per character per SFDC id. If there are only ~62 options, can you just construct a dict that maps each character to a number?

The `ord` and `chr` python functions would be great here, but they're not in the dbt context unfortunately

**Comment by drewbanin** [comment] 2018-07-18 13:09
@tayloramurphy just created [this](https://github.com/fishtown-analytics/dbt/issues/861) issue to track the agate type inference changes. Going to close this issue, but lmk if you have any questions about this either here or offline!

**Closed by drewbanin** 2018-07-18 13:09 UTC
