### ISSUE TITLE
BigQuery Snapshots fail with: UPDATE/MERGE must match at most one source row for each target row

### ISSUE THREAD

**Issue by brandfocus** [fishtown-analytics/dbt#1599] opened 2019-07-11 13:22 UTC
We are receiving the following error when running `dbt snapshot` on BigQuery with v0.14

``
UPDATE/MERGE must match at most one source row for each target row
``

**Comment by drewbanin** [comment] 2019-07-11 15:14
Hey @brandfocus - thanks for making this issue. On Slack, you noted:

> We weren’t using archives in 0.13, just checked the primary key and it is unique too

I want to figure out if this is a regression in 0.14.0, or if there's something funky otherwise happening with the snapshot implementation on BigQuery.

Can you show me the Snapshot code that you're using? As noted in Slack, this error is expected if the source query that's being snapshotted has a non-unique `unique_key`. This is actually a _great_ error to receive from the database, as dbt needs this `unique_key` to actually be unique! If it's non-unique, then the queries that dbt runs will result in duplicated entries being inserted into the snapshot destination table.

So, I'd love it if you could share:
1. your snapshot code (which strategy are you using)
2. confirmation that the `unique_key` is unique in your source dataset!

**Comment by brandfocus** [comment] 2019-07-15 17:55
`    {{
        config(
          target_database='analytics',
          target_schema='core',
          strategy='check',
          unique_key='id',
          check_cols=['value']
        )
    }}`

2. I can confirm the 'id' column is unique

**Comment by brandfocus** [comment] 2019-07-17 08:54
Guess this may be addressed in https://github.com/fishtown-analytics/dbt/pull/1614 @drewbanin

**Comment by drewbanin** [comment] 2019-07-17 14:22
@brandfocus I cooked up #1614 while trying to replicate the error that you're seeing. I actually think it solves a different problem though: the `check` logic (at least on BQ) would do something incorrect when the `check_cols` values were repeated, but I wasn't able to reproduce the specific error
```
UPDATE/MERGE must match at most one source row for each target row
```

Can you also tell me:
 - which version of dbt are you using? Is it `v0.14.0`, or a pre-release (like `v0.14.0rc1`)? How did you install dbt?
 - dbt merges on the `dbt_scd_id` column, which is where your duplicates appear to exist. This column is generated from a hash of the unique__key and check_cols. Can you tell me if the following query returns any rows with `count_instances` that are greater than `1`?

```sql
select
  to_hex(md5(concat(
    coalesce(cast(id as string), ''), '|',
    coalesce(cast(value as string), '')
  ))) as dbt_scd_id,
  count(*) as count_instances
from <source table>
group by 1
order by 2 desc
limit 10
```

This could happen if:
1. there is a hash collision (super unlikely)
2. there's some sort of pathologic thing happening here where your `value` and `id` columns collide (also probably unlikely)

To really dig into this, you'll want to snoop the `logs/dbt.log` file and find two queries. They'll look like:
```
create or replace table `{project}`.`{dataset}`.`{snapshot_name}__dbt_tmp`....
```
and 
```
insert into `{project}`.`{dataset}`.`{snapshot_name}__dbt_tmp` (dbt_change_type, dbt_scd_id, dbt_valid_to) ...
```

If you run these queries manually, then you can inspect the data that dbt is merging into the destination snapshot table. If you're able to do this, I'd be _really_ curious to know if the `dbt_scd_id` columns are duplicated in this table. If they are duplicated (which I imagine they are) then the next step is to figure out how the nature of the duplicates!

Let me know if you have any questions about any of this!

**Comment by drewbanin** [comment] 2019-07-23 01:31
Hey @brandfocus - did you have a chance to give this a spin? I'd love to fix this for an 0.14.1 patch release if it's an issue on dbt's end, but I'm a little bit stuck here without any further info!

Definitely let me know if you have any questions about finding / running these queries.

Thanks!

**Comment by brandfocus** [comment] 2019-07-23 12:56
```
select
  to_hex(md5(concat(
    coalesce(cast(id as string), ''), '|',
    coalesce(cast(value as string), '')
  ))) as dbt_scd_id,
  count(*) as count_instances
from <source table>
group by 1
order by 2 desc
limit 10
```

Returns:

```
Row | dbt_scd_id | count_instances |  
-- | -- | -- | --
1 | 26149083b7500f39e467cdf13f176fdb | 1 |  
2 | 42802023566dff338aa868b36a23c140 | 1 |  
3 | 8e800a7dd6d59ea0756d37b4d95acb40 | 1 |  
4 | c589bc911ee183c2e23e749ca0408a92 | 1 |  
5 | 442c5595a6854e783efac203c6f7a797 | 1 |  
6 | 906673e48a31cd7cf4f0c29b0a298db4 | 1 |  
7 | ae4643ca1a3e715353eeeff102592ef8 | 1 |  
8 | f5a56ced5f06d43eb0b2806503eeec1e | 1 |  
9 | 8a1a5c0f558ad9af9bca440350312fb1 | 1 |  
10 | 5aa5e431deeca2319288d9c0f5776c8c | 1
```


The following query returns `UPDATE/MERGE must match at most one source row for each target row`:

```
  merge into `marketing-analytics`.`core`.`snapshot_trafficdashboard_app_lt_dailykpis` as DBT_INTERNAL_DEST
    using `marketing-analytics`.`core`.`snapshot_trafficdashboard_app_lt_dailykpis__dbt_tmp` as DBT_INTERNAL_SOURCE
    on DBT_INTERNAL_SOURCE.dbt_scd_id = DBT_INTERNAL_DEST.dbt_scd_id

    when matched
     and DBT_INTERNAL_DEST.dbt_valid_to is null
     and DBT_INTERNAL_SOURCE.dbt_change_type = 'update'
        then update
        set dbt_valid_to = DBT_INTERNAL_SOURCE.dbt_valid_to

    when not matched
     and DBT_INTERNAL_SOURCE.dbt_change_type = 'insert'
        then insert (`id`, `date`, `year`, `kpi`, `country`, `channel`, `value`, `dbt_scd_id`, `dbt_updated_at`, `dbt_valid_from`, `dbt_valid_to`)
        values (`id`, `date`, `year`, `kpi`, `country`, `channel`, `value`, `dbt_scd_id`, `dbt_updated_at`, `dbt_valid_from`, `dbt_valid_to`)
    ;
```

**Comment by drewbanin** [comment] 2019-07-23 13:44
Ok - thanks for that @brandfocus.

The only way I can reproduce this particular merge error is when the source table (here: `snapshot_trafficdashboard_app_lt_dailykpis__dbt_tmp`) has duplicated values in the `dbt_scd_id` column. It definitely does not appear that you have duped values here... so i am pretty stumped.

Can you also just confirm for me that you're using 0.14.0 proper and not a pre-release (like `v0.14.0rc1`)? You can check with `dbt --version`

Really appreciate your help in getting to the bottom of this one

**Comment by brandfocus** [comment] 2019-07-23 15:22
```
installed version: 0.14.0
   latest version: 0.14.0

Up to date!
```

The only thing I can think of is should the __dbt_tmp tables be removed after the previous snapshot run? It looks like they are being persisted.

**Comment by brandfocus** [comment] 2019-07-23 15:57
@drewbanin I think this may be the issue:

```
SELECT * 
FROM `snapshot__dbt_tmp` 
WHERE dbt_change_type = 'update'
LIMIT 10
```

Results:


```
Row | dbt_change_type | id | date | year | kpi | country | channel | value | dbt_scd_id | dbt_unique_key | dbt_updated_at | dbt_valid_from | dbt_valid_to |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | update | null | null | null | null | null | null | null | 00003e3b9e5336685200ae85d21b4f5e | null | null | null | 2019-07-23 15:48:10.599989 UTC |  
2 | update | null | null | null | null | null | null | null | 00003e3b9e5336685200ae85d21b4f5e | null | null | null | 2019-07-23 15:48:10.599989 UTC |  
3 | update | null | null | null | null | null | null | null | 0000be009c77600279064ae75df2c91e | null | null | null | 2019-07-23 15:48:10.599989 UTC |  
4 | update | null | null | null | null | null | null | null | 0000d2040a01cdfa29b49abb8e54f4bf | null | null | null | 2019-07-23 15:48:10.599989 UTC |  
5 | update | null | null | null | null | null | null | null | 0000d2f55c93b84d8e2b0c65354a997c | null | null | null | 2019-07-23 15:48:10.599989 UTC |  
6 | update | null | null | null | null | null | null | null | 0000d2f55c93b84d8e2b0c65354a997c | null | null | null | 2019-07-23 15:48:10.599989 UTC |  
7 | update | null | null | null | null | null | null | null | 00011cd18d2b5ea921f61e2451295362 | null | null | null | 2019-07-23 15:48:10.599989 UTC |  
8 | update | null | null | null | null | null | null | null | 00015840c550e030e6f490551f1839e0 | null | null | null | 2019-07-23 15:48:10.599989 UTC |  
9 | update | null | null | null | null | null | null | null | 00015840c550e030e6f490551f1839e0 | null | null | null | 2019-07-23 15:48:10.599989 UTC |  
10 | update | null | null | null | null | null | null | null | 00021bc6d0d4b22a6220899089a9e97a | null | null | null | 2019-07-23 15:48:10.599989 UTC
```

**Comment by drewbanin** [comment] 2019-07-23 16:01
I see! Those `null` values are expected -- dbt only sets the destination `dbt_valid_to` column (joining on the `dbt_scd_id` field), so the other fields are intentionally left `null`.

Do you also see that these `dbt_scd_id` values are duplicated in your Snapshot destination table?

**Comment by brandfocus** [comment] 2019-07-23 16:04
Yes, they appear to be duplicated in the destination snapshot table

```
SELECT dbt_scd_id, COUNT(dbt_scd_id) FROM `snapshottable`
GROUP BY dbt_scd_id
HAVING COUNT(dbt_scd_id) > 1
```

**Comment by brandfocus** [comment] 2019-07-23 16:10
```
SELECT * 
FROM `snapshottable`
WHERE dbt_scd_id = '0000d2f55c93b84d8e2b0c65354a997c'
```

e.g:

```
1 | 3947807b2111ca976a0023faa439bc98 | 2018-05-30 | 2018 | CPO | Poland | email | x | 0000d2f55c93b84d8e2b0c65354a997c | 2019-07-10 16:33:01.253163 UTC | 2019-07-10 16:33:01.253163 UTC | null |  
2 | a1f29d83de6884f448c62619f19f368d | 2018-09-07 | 2018 | CPO | Singapore | email | x | 0000d2f55c93b84d8e2b0c65354a997c | 2019-07-10 16:33:01.253163 UTC | 2019-07-10 16:33:01.253163 UTC | null |  
3 | 28b35cc382f3a9c592a5944df727c849 | 2019-06-25 | 2019 | CPO | Germany | email | x | 0000d2f55c93b84d8e2b0c65354a997c | 2019-07-10 16:33:01.253163 UTC | 2019-07-10 16:33:01.253163 UTC | null


```

**Comment by drewbanin** [comment] 2019-07-24 16:58
This was due to the snapshot table initially being built with a pre-release of dbt v0.14.0. The failure mode present here does not occur in the final release of dbt v0.14.0. Closing!

Thanks for your help in debugging this one @brandfocus

**Closed by drewbanin** 2019-07-24 16:58 UTC
Labels: Snapshots, bigquery, more information needed
