### ISSUE TITLE
Case issue on materialized='table'

### ISSUE THREAD

**Issue by st3vemartin** [fishtown-analytics/dbt#586] opened 2017-11-08 14:29 UTC
When executing my project against Redshift I was having an issue with the table not being dropped / recreated.  It turned out that it was a case sensitive issue, where dbt would create the table name as "Account", but was (most likely) dropping a table if exists of "account" - Giving me a pesky table exists error.  I changed my sql file name from "Account" to "account" and the table exists error cleared.

**Comment by cmcarthur** [comment] 2017-11-08 15:04
thanks @st3vemartin! it's likely that this is caused by inconsistent use of `adapter.quote` in materialization code. someone will take a look.

**Comment by ridhoq** [comment] 2018-03-11 01:48
Hey there, I was looking around for a good issue to start contributing and I found this.

Is this the [line](https://github.com/fishtown-analytics/dbt/blob/94033d22f81ff2b03061a2cf27accd3736715a50/dbt/include/global_project/macros/adapters/redshift.sql#L66) where `adapter.quote` would need to be used?

What kind of tests should be added along with this fix? I don't see a Redshift unit test - should we start a new one?

**Comment by drewbanin** [comment] 2018-03-11 15:25
hey @ridhoq! It's not totally clear what the correct behavior should be here. We can

1) make sure we quote identifiers everywhere, or
2) don't quote identifiers _anywhere_

There's another complication here: Databases like Snowflake treat identifiers differently: https://github.com/fishtown-analytics/dbt/issues/567

Let me give this some more thought -- I _think_ we'll end up wanting to _not_ quote identifiers

**Comment by ridhoq** [comment] 2018-03-11 16:33
hey @drewbanin! My (perhaps superficial) concern with not quoting any identifiers is that a user could supply a reserved word as an identifier which could result in the db throwing an error. But, I'm obviously not familiar with the codebase and we may already be handling this elsewhere - I'll defer to you :)

**Comment by drewbanin** [comment] 2018-03-11 16:43
yeah, good point @ridhoq. That was our initial impetus for quoting these identifiers! I think though, that folks probably shouldn't be naming their models or columns after database reserved words. We have another feature, [alias](https://github.com/fishtown-analytics/dbt/pull/651) that can help with this too.

We need to be consistent with quoting everywhere, and I like the idea of enabling users to opt-in to quoting rather than having dbt decide for them. This isn't such a huge deal on Redshift, but there's a big difference between `table_name` and `"table_name"` on Snowflake, for instance. I'm definitely open to alternatives!

**Comment by ridhoq** [comment] 2018-03-12 05:10
@drewbanin gotcha. I agree - users _shouldn't be_ using identifiers with database reserved words. The only time I think it could trip somebody up is if they were to switch to a different database with their same models and find that one of the identifiers they used previously is a reserved word in the new database that they're using. But maybe that's an extreme edge case as I can't even think of an example lol

Opting into quoting sounds like a very reasonable approach (and would solve the above edge case). I would want to make sure that it's easy to implement new database engines as well since each database has their own weird rules around escaping/quoting - SQL Server comes to mind. Do you see this "force quoted identifiers" setting as a command line argument or a setting in the profile?

**Comment by drewbanin** [comment] 2018-04-26 19:41
fixed by: https://github.com/fishtown-analytics/dbt/pull/727 (going out in 0.10.1)

**Closed** 2018-06-28 17:36 UTC
Labels: bug, good first issue
