### ISSUE TITLE
Handle errors more gracefully in on-run-start/end context

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#1266] opened 2019-01-29 16:10 UTC
### Issue description
If errors occur in on-run-start/end, dbt will not provide the usual end of run summary. As such, errors that occurred during the run will not be shown.

Example output:
```
07:30:13 | 34 of 34 ERROR relation analytics.my_model......... [ERROR]
Database error while running on-run-end
Database Error
SSL SYSCALL error: EOF detected
```

### System information
The output of `dbt --version`:
```
v0.12.2
```

**Comment by gmile** [comment] 2021-01-29 17:43
I don't think it's the case anymore. I am experiencing `SSL SYSCALL error: EOF detected` sometimes too. The summary doesn't get garbled like in the example above.

**Comment by jtcohen6** [comment] 2021-02-01 10:59
Good point @gmile. I think this improved in dbt v0.14.0 (July 2019) with the addition of stdout logging for `on-run-start` and `on-run-end` (#1440). I'm going to close this issue as an effective duplicate of #696.

**Closed by jtcohen6** 2021-02-01 10:59 UTC
Labels: bug, duplicate
