### ISSUE TITLE
dbt doesn't tag models in generated docs

### ISSUE THREAD

**Issue by escapedoc** [fishtown-analytics/dbt#2957] opened 2020-12-15 18:15 UTC
### Describe the bug
Tagging models not working in generated docs.
I attach the screen of my small .yml
When I generate docs, those tags a re not applied to models...

### Steps To Reproduce
1. Create one source.yml and add tags to sources there. Generate docs get these tags
2. Create ob model.yml file with one or two models, that will have queries, that use sources defined in step 1.
3. run:
- dbt clean
- dbt compile
- dbt docs generate
- dbt serve
4. GO to docs and check the sources and models. Models would be untagged and sources tagged
5. As an addition to these graph will not show tagged sources, cause it has only one untag filter. I've started these thread in slack #begginers channel [could be found here](https://getdbt.slack.com/archives/CBSQTAPLG/p1608049886013000)

### Expected behavior
Models and sources should be tagged. And I can filter them on graph in docs

### Screenshots and log output
models.yml:
![image](https://user-images.githubusercontent.com/36753884/102254367-931fd000-3f19-11eb-8d8b-518c1be94a12.png)

What's showing in docs:
![image](https://user-images.githubusercontent.com/36753884/102255460-2c9bb180-3f1b-11eb-924f-202167a9688c.png)

### System information
**Which database are you using dbt with?**
-  bigquery

**The output of `dbt --version`:**
installed version: 0.18.1
   latest version: 0.18.1

Up to date!

Plugins:
  - bigquery: 0.18.1
  - postgres: 0.18.1
  - redshift: 0.18.1
  - snowflake: 0.18.1

**The operating system you're using:**
Windows 10
**The output of `python --version`:**
Python 3.7.9

**Comment by jtcohen6** [comment] 2020-12-15 20:44
Thanks for opening @escapedoc! This is more confusing than it should be, because it's at the intersection of some genuine bugs, and then some behavior that is working as intended but feels a bit inconsistent or counterintuitive.

First off, the bugs:
- Tagged sources not showing up in the DAG was a bug. This is already fixed in v0.19.0b1 and will be included in v0.19.0 (https://github.com/fishtown-analytics/dbt-docs/pull/139)
- Though you don't mention it here, the same issue applied to tagged data tests, that will be fixed for v0.19.0 as well (https://github.com/fishtown-analytics/dbt-docs/pull/157)

Now, the tricky behavior: For reasons of technical complexity, it is not possible to tag _models_ inside a resource YAML file. (It is possible to tag sources, columns, and tests in that type of file.) Check out the docs on the [`tags` property](https://docs.getdbt.com/reference/resource-properties/tags/):

> Note: To tag a model, use the [tag _configuration_](tag configuration).
> 
> **models/schema.yml**
> ```
> version: 2
> 
> models:
>   - name: model_name
>     # tags: [] # this is not supported — check out the above link for more info
> ```

Instead, you'll want to _configure_ models with tags, either with an in-file `config()` block:
```sql
{{ config(tags = ['hits']) }}
```
Or in `dbt_project.yml`:
```yml
models:
  my_project:
    staging:
      ga:
        ga__hits:
          +tags:
            - hits
```

Why does this distinction between "node configs" and "resource properties" exist? Good question. I'd like to reconcile the two as much as possible (#2401). Today, the former prescriptively say how a model should be built, whereas the latter describes attributes of that model. That's still sort of a rough generalization—and then there's `tags`, which can be a config _or_ a property but never quite both at the same time.

I'm going to close this issue, since it doesn't represent a novel or unknown bug, and since the real resolution to the confusion is already on our v1.0 roadmap.

**Closed by jtcohen6** 2020-12-15 20:44 UTC
Labels: bug
