### ISSUE TITLE
`dbt deps` requires environment variables to be set

### ISSUE THREAD

**Issue by robbruce** [fishtown-analytics/dbt#3136] opened 2021-03-01 16:28 UTC
### Describe the bug

When using `dbt deps`, this requires for any environment variables declared with the `env_var` macro to be defined.

### Steps To Reproduce

Use `env_var` in a profiles file, or dbt_project file, and run `dbt deps` without that environment variable existing.

### Expected behavior

Shouldn't need environment variables, should only depend on what's declared in `packages.yml` file.

### Screenshots and log output

Error when following steps to re-produce

```
Encountered an error:
Compilation Error
  Could not render {{ env_var('MY_ENV_VAR') }}: Env var required but not provided: 'MY_ENV_VAR'
```

### System information

Shouldn't matter!

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.19.0
   latest version: 0.19.0

Up to date!

Plugins:
  - snowflake: 0.19.0
```

**The operating system you're using:**

**The output of `python --version`:**
```
Python 3.8.5
```
### Additional context

Package management should only work with the packages, and not depend on anything else really.

**Comment by jtcohen6** [comment] 2021-03-02 10:36
Thanks for opening @robbruce! This is a totally reasonable request, and I agree that commands such as `deps` and `clean`, which do not require a valid connection profile, should not fail on account of a missing env var.

I'm going to close this issue only because it's a duplicate of #2368. You can check out the workaround proposed there in the meantime: as long as you pass a placeholder default value to `"{{ env_var('MY_ENV_VAR', 'not-set') }}"`, dbt will not return an error message.

**Closed by jtcohen6** 2021-03-02 10:36 UTC
Labels: bug, duplicate
