### ISSUE TITLE
Incorrect warning about partition_by in dbt_project.yml

### ISSUE THREAD

**Issue by walshie4** [fishtown-analytics/dbt#2331] opened 2020-04-15 23:32 UTC
### Describe the bug
When defining `partition_by` in the new object syntax for a collection of models in our `dbt_project.yml` file like so (simplified for sharing):
```yml
models:
  sample:
    partition_by:
      field: 'timestamp'
      data_type: 'timestamp'
    cluster_by: 'user_id'
```

Causes `dbt compile` to output:
```
Running with dbt=0.16.1
WARNING: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.sample.partition_by
```

However the files which end up in `target/run/` have the proper partition statements in the output:
```sql
  partition by date(timestamp)
  cluster by user_id
```

Commenting out or removing that block removes that statement and makes it invalid.

### Steps To Reproduce
Run `dbt compile` with a `parition_by` object defined in `dbt_project.yml`

### Expected behavior
I would expect this warning to not be printed because the config values are in fact being applied to resources.

### Screenshots and log output
See above

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.16.1
   latest version: 0.16.1

Up to date!
```

**The operating system you're using:**
```
MacOS 10.15.3
```

**The output of `python --version`:**
```
Python 3.7.3
```

**Comment by drewbanin** [comment] 2020-04-16 13:19
Thanks for the report @walshie4! The big issue here is that dbt's `models:` config syntax is ambiguous. The `partition_by` config is a dict, so it _looks_ like a config of the path `models/partition_by/` with the configs:
```
      field: 'timestamp'
      data_type: 'timestamp'
```

We're actually working on a general fix for this presently -- check it out in #2300! 

I'm going to close out this issue just because #2300 does a good job of tracking the required changes and is already in-progress, but I really appreciate you sharing this concrete failure mode with us! Please feel free to let us know what you think of the approach outlined in #2300 :)

**Closed by drewbanin** 2020-04-16 13:19 UTC
Labels: bigquery, bug, duplicate

**Comment by ran-eh** [comment] 2020-06-07 04:32
Hi @drewbanin .  Tracking the relevant links, I am not sure what the resolution is exactly.  Am I correct to assume that this will be resolved by introducing the dbt_project version 2, and that that has not happened yet (0.17?), and that to be able to use partition_by at a folder level we will need to migrate dbt_project.yml to version 2, adding `config:` everywhere?  If so, what is the time line for this, and in the meantime is it possible to at least make version 1 recognize partition_by as a built in instead of interpreting it as a path element?

**Comment by drewbanin** [comment] 2020-06-08 13:21
hey @ran-eh - I think you're general idea is right! We nixed the `config:` syntax and instead are using a `+` syntax.

In v0.17.0 (due out today) you will be able to specify:
```
models:
  sample:
    +partition_by:
      field: 'timestamp'
      data_type: 'timestamp'
    cluster_by: 'user_id'
```

The `+` in `+partition_by` will denote that this is a dict-config, not a dictionary of configs :)

You will indeed need to upgrade to 0.17.0 to take advantage of this change. Docs to come alongside the release :)

**Comment by ran-eh** [comment] 2020-06-08 16:50
Awesome - so it is backwards compatible is most situation?  No more need for config_version = 2?

**Comment by drewbanin** [comment] 2020-06-08 16:57
Sorry - you'll also need to supply `config-version: 2` - this change is not backwards compatible. You'll need to be on 0.17.0 for sure. The pre-release docs for this can be found [here](https://deploy-preview-158--docs-getdbt-com.netlify.app/docs/guides/migration-guide/upgrading-to-0-17-0/#a-new-dbt_projectyml-config-version)

**Comment by dreinon** [comment] 2023-03-27 11:04
This is still happening to me today with `config-version: 2`. Am I doing something wrong?
Thanks in advance!

![image](https://user-images.githubusercontent.com/67071425/227923941-00117c53-bf41-4139-965d-0787406f970e.png)

![image](https://user-images.githubusercontent.com/67071425/227923958-ea1cef13-f667-4b55-9c21-bfcc894c0318.png)

**Comment by jtcohen6** [comment] 2023-03-27 11:20
@dreinon That's not a bug with `dbt-core`, but rather a mismatch with [`dbt-jsonschema`](https://github.com/dbt-labs/dbt-jsonschema)! Probably because the `partition_by` configuration is specific to certain data platforms / adapters, and not defined in the `dbt-core` standard.

**Comment by dreinon** [comment] 2023-03-27 11:25
@jtcohen6 Right! Is making dbt-jsonschema compatible with adapters something you have thought about? Maybe specifying some config like, in this case `platform: bigquery`
