### ISSUE TITLE
0.20.0b1 doesn't compile all ephemeral models into CTEs

### ISSUE THREAD

**Issue by joshpeng** [fishtown-analytics/dbt#3357] opened 2021-05-14 21:41 UTC
### Describe the bug
`ref()`ing ephemeral models in dbt 0.20.0b1 misses creating some of them as CTEs in 0.20.0b1.

### Steps To Reproduce
Create the following folder structure under `models`:

```
models
   _staging
        stg_ephemeral_a.sql
        stg_ephemeral_b.sql
   _transform
        tf_joined.sql
```

Use this as the contents of the `stg_ephemeral_a.sql` and `stg_ephemeral_b.sql`:
```
{{
    config(
        materialized = 'ephemeral'
    )
}}

select 1
```

Use this for `tf_joined.sql`
```
{{
    config(
        materialized = 'incremental',
        unique_key = 'date'
    )
}}

with a as (
    select * from {{ ref('stg_ephemeral_a') }}
),
b as (
    select * from {{ ref('stg_ephemeral_b') }}
)
select
    current_date as date,
    a.*
    b.*
from a
full outer join b
    on 1=1
```

### Expected behavior
We are expecting both the ephemeral staging models to be injected as CTEs into the compiled code for `tf_joined`, but in dbt 0.20.0b1, it only injects the `stg_ephemeral_b` and skips the first one.

The compiled code is as follows:
```
with __dbt__cte_stg_ephemeral_b as (


select 1
),a as (
    select * from __dbt__cte__stg_ephemeral_a
),
b as (
    select * from __dbt__cte__stg_ephemeral_b
)
select
    current_date as date,
    a.*,
    b.*,
from a
full outer join b
    on 1=1
```

If we however downgrade dbt back to 0.19.1, the exact same code will generate this as the compiled code. This is correct behavior and has both staging CTEs injected.
```
with __dbt__CTE_stg_ephemeral_a as (


select 1
),  __dbt__CTE__stg_ephemeral_b as (


select 1
),a as (
    select * from __dbt__CTE__stg_ephemeral_a
),
b as (
    select * from __dbt__CTE__stg_ephemeral_b
)
select
    current_date as date,
    a.*,
    b.*,
from a
full outer join b
    on 1=1
```

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
dbt 0.20.0b1
```

**The operating system you're using:**
macOS

**The output of `python --version`:**
python 3.7

**Comment by jtcohen6** [comment] 2021-05-16 17:34
Really appreciate you opening, @joshpeng!

This is a duplicate of https://github.com/fishtown-analytics/dbt/issues/3317, which we fixed in https://github.com/fishtown-analytics/dbt/pull/3318. This one is on us: we included a fix for the bug in v0.19.1 / the `0.19.latest` branch, but the fix didn't make it into `develop` ahead of cutting v0.20.0-b1.

**Closed by jtcohen6** 2021-05-16 17:34 UTC
Labels: bug, duplicate

**Comment by joshpeng** [comment] 2021-05-21 21:26
Thanks for the reply @jtcohen6. Really appreciate all the work going on. My team unfortunately can't go back to 0.19.1 due to old python dependencies that are disallowed in our build system, so we were curious if there was a rough estimate for 0.20.0rc1's timeline?

**Comment by jtcohen6** [comment] 2021-05-25 04:31
@joshpeng Understood. We're definitely planning to put out another prerelease this week. Whether that's 0.20.0b2 or 0.20.0rc1 will depend on how many pieces are still outstanding in a few day's time.
