### ISSUE TITLE
Can't describe a model with config

### ISSUE THREAD

**Issue by philippe-lavoie** [fishtown-analytics/dbt#1922] opened 2019-11-15 21:02 UTC
### Describe the bug
The following is not reflected inside the website

```
{{
  config(
    description = "whatever"
  )
}}
```

### Steps To Reproduce
Add the above to a model

### Expected behavior
If I specify description, I should be able to see it inside the generate website.

### Screenshots and log output
N/A

### System information

**The output of `dbt --version`:**
```
installed version: 0.14.4
   latest version: 0.14.4

Up to date!
```

**The operating system you're using:**
Windows

**The output of `python --version`:**
Python 3.7.3

### Additional context
None

**Comment by drewbanin** [comment] 2019-11-17 16:28
Hey @philippe-lavoie - `description` is not currently supported as a `config` for models, so the behavior you're seeing is expected.

I'm open to the idea of supporting `description` in a `config` block. You'd only be able to set the description for a model, not the columns in the model, but that might be acceptable for some use cases. We'd also need to think about precedence -- what happens if a description is provided both in `config()` and in the `description` field in a `schema.yml` file? I don't think it's obvious which one of those should take precedence -- maybe it should be an error to supply it in both places?

I don't really perceive a need for this change - can you tell me a little more about your use case?  Happy to discuss this further!

**Comment by philippe-lavoie** [comment] 2019-11-18 14:14
I guess it was out of ease for me, I'm creating a postgresql-to-dbt tool. It scans a database and it updates the dbt_project file and creates models for the full database. After reading the best practices, I decided to also allow sources to be documented inside the schema.yml file however when I do that inside a folder and there are no sql files, then there is a warning from DBT. 

To remove that, I generate a delete_me_*.sql file in each folder and wanted to document the fact that the file should be deleted without modifying the schema file itself. I can definitely update the schema file, however the goal was for the user to delete it as soon as it has a sql file in it and therefore no need to also update the schema file. I understand it's a small use case.

In terms of precedence, I'd say the SQL file takes precedence over the schema file like it does for the project file.

**Comment by drewbanin** [comment] 2019-11-18 14:25
ah! ok - we can totally fix that warning - do you happen to have an example of what the warning looks like handy?

**Comment by philippe-lavoie** [comment] 2019-11-18 17:25
The warning looks like:

```
WARNING: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 2 unused configuration paths:
- models.test_package.Operational
- models.test_package.Sales
```

The above was when there is no .sql files in both folders. It only has a schema file with a lot of sources.

**Comment by drewbanin** [comment] 2019-11-18 17:26
I see! Ok - that's super helpful - thanks for the additional info here. We'll check it out!

**Comment by drewbanin** [comment] 2019-11-20 17:01
@philippe-lavoie this warning should only show up if there are model configurations defined in the `dbt_project.yml` file which do not map to any dbt models.

That could happen if you have a file like:
```
models/Sales/schema.yml
```

and a `dbt_project.yml` file with:
```
models:
  my_project:
    Sales:
      materialized: view
```

Here, dbt would warn you that the `materialized: view` config does not apply to any models. If that's the behavior you're seeing, then I think this is working as intended. If you're seeing something else here, I'd love to learn more about the details. Thanks!

**Comment by drewbanin** [comment] 2019-11-26 02:18
closing this one - `description` doesn't belong in the model config, and model warnings are working as appropriate as far as i can tell.

**Closed by drewbanin** 2019-11-26 02:18 UTC
Labels: enhancement
