### ISSUE TITLE
Jinja evaluating vars per model instead of per project when var defined at the project level.

### ISSUE THREAD

**Issue by mgenereu** [fishtown-analytics/dbt#2386] opened 2020-05-01 16:40 UTC
### Describe the bug
Added the following to dbt_project.yml
```yaml
models:
  vars:
    exec_timestamp: "{{ modules.datetime.datetime.now().strftime('%s') }}"
  [redacted project name]:
    materialized: "table"
    post-hook:
      - sql: "{{ copy_to_stage('@[redacted snowflake stage]', this) }}"
        transaction: false
```
### Steps To Reproduce
Run multiple models.

### Expected behavior
I expected the exec_timestamp Jinja to run once for all models.

### Screenshots and log output
Here's the two folders created in S3 created by running two models at the same time.
![Screen Shot 2020-05-01 at 9 25 56 AM](https://user-images.githubusercontent.com/21925/80821549-d0ec0600-8b8d-11ea-9b74-ae97be3f54a7.png)

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.16.1
   latest version: 0.16.1

Up to date!
```

**The operating system you're using:**
```
Darwin [redacted computer name] 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
```

**The output of `python --version`:**
```
Python 3.7.7
```

**Comment by mgenereu** [comment] 2020-05-01 16:56
To clarify,  my `COPY TO statge` macro uses the `exec_timestamp` variable.

**Comment by drewbanin** [comment] 2020-05-02 13:33
thanks for the report @mgenereu!

I think that dbt is operating as intended here. Maybe instead of using the wallclock time, you could use the [run_started_at](https://docs.getdbt.com/docs/writing-code-in-dbt/jinja-context/run_started_at/) variable instead? That should give you a consistent timestamp throughout the duration of the run

I'm going to close this one out, but please let me know if you have any further thoughts or questions on this one

**Closed by drewbanin** 2020-05-02 13:33 UTC
Labels: bug

**Comment by mgenereu** [comment] 2020-05-02 14:29
I don't know how I missed that. I ran down that list. Thank you for responding!
